{{ if and .Values.scheduler.enabled .Values.scheduler.extraServices -}}
{{- range $serviceType, $deploymentConfig := .Values.scheduler.extraServices -}}
{{- $deploymentConfig = include "swh.scheduler.deploymentConfig"
                          (dict "deploymentConfig" $deploymentConfig
                                "Values"           $.Values) | fromYaml -}}
{{- $configurationDict := dict "configuration" $deploymentConfig
                               "name"          (print "extra-services-configuration-" $serviceType)
                               "Values"        $.Values -}}
{{- include "swh.scheduler.extraService.configmap" $configurationDict -}}
{{- end }}
{{- end -}}
