{{ $namespace := .Values.namespace }}
{{- with .Values.scheduler }}
{{- if and .enabled .journalClient.enabled -}}
{{ $journalClientOverrides := deepCopy (get .journalClient "journalClientOverrides" | default dict) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-journal-client-configuration-template
  namespace: {{ $namespace }}
data:
  config.yml.template: |
    {{- include "swh.schedulerConfiguration"
                  (dict "configurationRef" .schedulerConfigurationRef
                        "Values"           $.Values) | nindent 4 }}

    {{- include "celery.configuration"
                  (dict "configurationRef" .celeryConfigurationRef
                        "Values"           $.Values) | nindent 4 }}

    {{- include "swh.journalClientConfiguration"
                  (dict "configurationRef" .journalClient.journalClientConfigurationRef
                        "overrides"        $journalClientOverrides
                        "Values"           $.Values) | nindent 4 }}

{{- end }}
{{- end }}
