{{- define "coarNotify.config.fromYaml" -}}
{{- $coarNotifyConfiguration := (dict) -}}
{{- $coarNotifyConfiguration = include "swh.storageConfiguration" (dict
                                      "service" "storage"
                                      "configurationRef" .Values.coarNotify.storageConfigurationRef
                                      "Values" .Values) | fromYaml | mustMerge $coarNotifyConfiguration -}}
{{- $coarNotifyConfiguration = mustMerge $coarNotifyConfiguration (dict "allowed_hosts" .Values.coarNotify.allowed_hosts ) -}}
{{- $extraConfiguration := (dict) -}}
{{- $extraConfiguration := include "swh.service.fromYaml" (dict "configurationRef" .Values.coarNotify.extraConfigRef
                                      "Values" .Values) | fromYaml | mustMerge $extraConfiguration  }}
{{- $coarNotifyConfiguration = mustMerge $coarNotifyConfiguration $extraConfiguration -}}
{{- $djangoConfiguration := dict "private" (dict) -}}
{{- $databaseConfiguration := include "django.postgresql" (dict "configurationRef" .Values.coarNotify.databaseCoarNotifyConfigurationRef
                                              "Values" .Values) | fromYaml -}}
{{- $_ := set $djangoConfiguration.private "db" $databaseConfiguration -}}
{{- $_ := set $djangoConfiguration.private "secret_key" "${DJANGO_SECRET_KEY}" -}}
{{- $coarNotifyConfiguration = mustMerge $coarNotifyConfiguration $djangoConfiguration -}}
{{ $coarNotifyConfiguration | toYaml }}
{{- end -}}
{{- define "coarNotify.configmap" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .serviceType }}-template
  namespace: {{ .Values.namespace }}
data:
  config.yml.template: |
    {{- include "coarNotify.config.fromYaml" (dict "Values" .Values) | nindent 4 -}}
{{ end }}
