{{- if .Values.coarNotify.enabled -}}
{{- $serviceName := "coar-notify" -}}
{{- $configurationChecksum := include "coarNotify.configmap" (dict "serviceType" $serviceName "Values" .Values) | sha256sum -}}
{{- $affinity := .Values.coarNotify.deployment.affinity -}}
{{- $nodeSelector := .Values.coarNotify.deployment.nodeSelector | default dict -}}
{{- $priorityClassName := cat .Values.namespace "-" .Values.coarNotify.deployment.priorityClassName | nospace -}}
{{- $requestedCpu := get .Values.coarNotify.deployment "requestedCpu" -}}
{{- $requestedMemory := get .Values.coarNotify.deployment "requestedMemory" -}}
{{- $limitedCpu := get .Values.coarNotify.deployment "limitedCpu" -}}
{{- $limitedMemory := get .Values.coarNotify.deployment "limitedMemory" -}}
{{- $replicas := .Values.coarNotify.replicas | default 1 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
      annotations:
        # Force a rollout upgrade if the configuration changes
        checksum/config: {{ $configurationChecksum }}
    spec:
      securityContext:
        fsGroup: 1000
      {{- if $nodeSelector }}
      nodeSelector:
        {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      priorityClassName: {{ $priorityClassName }}
      initContainers:
        - name: prepare-configuration
          image: {{ .Values.swh_utils_image }}:{{ .Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          env:{{ include "swh.secrets.envFromDeploymentConfig" (dict "deploymentConfig" .Values.coarNotify
                                                                      "Values" .Values) | nindent 10 }}
          command:
            - /entrypoints/prepare-configuration.sh
          volumeMounts:
            - name: config-utils
              mountPath: /entrypoints
              readOnly: true
            - name: configuration
              mountPath: /etc/swh
            - name: configuration-template
              mountPath: /etc/swh/configuration-template
        {{- if .Values.coarNotify.migrationsEnabled }}
        - name: do-migration
          image: {{ .Values.swh_coar_notify_image }}:{{ .Values.swh_coar_notify_image_version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SWH_CONFIG_FILENAME
              value: /etc/swh/config.yml
          command:
            - django-admin
          args:
            - migrate
            - --settings=swh.coarnotify.settings.production
          volumeMounts:
            - name: configuration
              mountPath: /etc/swh
        {{- end }}
      containers:
        - name: {{ $serviceName }}
          resources:
            requests:
              memory: {{ $requestedMemory | default "512Mi" }}
              cpu: {{ $requestedCpu | default "500m" }}
            {{- if or $limitedCpu $limitedMemory }}
            limits:
              {{- if $limitedMemory }}
              memory: {{ $limitedMemory }}
              {{- end }}
              {{- if $limitedCpu }}
              cpu: {{ $limitedCpu }}
              {{- end }}
            {{- end }}
          command:
            - /opt/swh/entrypoint.sh
          image: {{ .Values.swh_coar_notify_image }}:{{ .Values.swh_coar_notify_image_version }}
          imagePullPolicy: IfNotPresent
          env:
          - name: SWH_LOG_LEVEL
            value: {{ .Values.coarNotify.logLevel | default "INFO" }}
          - name: SWH_CONFIG_FILENAME
            value: /etc/swh/config.yml
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
      volumes:
        - name: configuration
          emptyDir: {}
        - name: configuration-template
          configMap:
            name: {{ $serviceName }}-template
            defaultMode: 0777
            items:
            - key: "config.yml.template"
              path: "config.yml.template"
        - name: config-utils
          configMap:
            name: config-utils
            defaultMode: 0555
{{ end }}
