{{ if and .Values.coarNotify.enabled .Values.coarNotify.ingress.enabled -}}
{{- include "swh.ingress" (dict "Values"        .Values
                                "serviceType"   "coar-notify"
                                "configuration" .Values.coarNotify) -}}
{{ end }}