{{ if .Values.coarNotify.enabled -}}
{{- include "swh.service" (dict "Values"        .Values
                                "serviceType"   "coar-notify"
                                "configuration" .Values.coarNotify) -}}
{{- end -}}
