{{ if .Values.coar_notify.enabled -}}
{{- include "swh.service" (dict "Values"        .Values
                                "serviceType"   "coar-notify"
                                "configuration" .Values.coar_notify) -}}
{{- end -}}
