{{- if and .Values.coarNotify.enabled .Values.coarNotify.worker.enabled -}}
{{- $deployment_config := mustMerge dict .Values.coarNotify.worker.deployment .Values.coarNotify.deployment -}}
{{- $workerConfig := mustMerge dict .Values.coarNotify.worker (omit .Values.coarNotify "worker") -}}
{{- $serviceName := "coar-notify-worker" -}}
{{- $configurationChecksum := include "coarNotifyWorker.configmap" (dict "serviceType" $serviceName "Values" .Values) | sha256sum -}}
{{- $affinity := $deployment_config.affinity -}}
{{- $nodeSelector := $deployment_config.nodeSelector | default dict -}}
{{- $priorityClassName := cat .Values.namespace "-" ($deployment_config.priorityClassName) | nospace -}}
{{- $requestedCpu := get $deployment_config "requestedCpu" -}}
{{- $requestedMemory := get $deployment_config "requestedMemory" -}}
{{- $limitedCpu := get $deployment_config "limitedCpu" -}}
{{- $limitedMemory := get $deployment_config "limitedMemory" -}}
{{- $replicas := $deployment_config.replicas | default 1 -}}
{{- $use_json_logger := get .Values.coarNotify.worker "useJsonLogger" | default true -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
      annotations:
        # Force a rollout upgrade if the configuration changes
        checksum/config: {{ $configurationChecksum }}
    spec:
      securityContext:
        fsGroup: 1000
      {{- if $nodeSelector }}
      nodeSelector:
        {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if and .Values.podPriority.enabled $priorityClassName }}
      priorityClassName: {{ $priorityClassName }}
      {{- end }}
      initContainers:
        - name: prepare-configuration
          image: {{ .Values.swh_utils_image }}:{{ .Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          env: {{- include "swh.secrets.envFromDeploymentConfig" (dict "deploymentConfig" $workerConfig
                                                                      "Values" .Values) | nindent 10 }}
          command:
            - /entrypoints/prepare-configuration.sh
          volumeMounts:
            - name: config-utils
              mountPath: /entrypoints
              readOnly: true
            - name: configuration
              mountPath: /etc/swh
            - name: configuration-template
              mountPath: /etc/swh/configuration-template
      containers:
        - name: {{ $serviceName }}
          resources:
            requests:
              memory: {{ $requestedMemory | default "512Mi" }}
              cpu: {{ $requestedCpu | default "500m" }}
            {{- if or $limitedCpu $limitedMemory }}
            limits:
              {{- if $limitedMemory }}
              memory: {{ $limitedMemory }}
              {{- end }}
              {{- if $limitedCpu }}
              cpu: {{ $limitedCpu }}
              {{- end }}
            {{- end }}
          command:
            - /opt/swh/entrypoint.sh
          image: {{ .Values.swh_coar_notify_worker_image }}:{{ .Values.swh_coar_notify_worker_image_version }}
          imagePullPolicy: IfNotPresent
          env:
          - name: STATSD_HOST
            value: {{ $.Values.statsdExternalHost | default "prometheus-statsd-exporter" }}
          - name: STATSD_PORT
            value: {{ $.Values.statsdPort | default "9125" | quote }}
          - name: STATSD_TAGS
            value: deployment:coar-notify-worker
          - name: MAX_TASKS_PER_CHILD
            value: {{ get $deployment_config "maxTasksPerChild" | default 1 | quote }}
          - name: SWH_LOG_LEVEL
            value: {{ get $deployment_config "logLevel" | default "INFO" | quote }}
          - name: SWH_CONFIG_FILENAME
            value: /etc/swh/config.yml
          {{- if $use_json_logger }}
          - name: SWH_LOG_CONFIG
            value: /etc/swh/logging-configuration.yml
          {{- end }}
          {{- if .Values.sentry.enabled }}
          - name: SWH_SENTRY_ENVIRONMENT
            value: {{ $.Values.sentry.environment }}
          - name: SWH_MAIN_PACKAGE
            value: swh.coarnotify
          - name: SWH_SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.coarNotify.sentry.secretKeyRef }}
                key: {{ .Values.coarNotify.sentry.secretKeyName }}
                # 'name' secret must exist & include key "host"
                optional: false
          {{- end }}
          - name: SWH_SENTRY_DISABLE_LOGGING_EVENTS
            value: "true"
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
          {{ if $use_json_logger }}
          - name: configuration-template
            mountPath: /etc/swh/logging-configuration.yml
            subPath: logging-configuration.yml
            readOnly: true
          {{ end }}
      volumes:
        - name: configuration
          emptyDir: {}
        - name: configuration-template
          configMap:
            name: {{ $serviceName }}-template
            defaultMode: 0777
            items:
            - key: "config.yml.template"
              path: "config.yml.template"
            {{ if $use_json_logger }}
            - key: "logging-configuration.yml"
              path: "logging-configuration.yml"
            {{ end }}
        - name: config-utils
          configMap:
            name: config-utils
            defaultMode: 0555
{{- end -}}
