{{- if (and .Values.coarNotify.enabled .Values.coarNotify.worker.enabled) -}}
{{- include "coarNotifyWorker.configmap" (dict
      "serviceType" "coar-notify-worker"
      "Values" $.Values) -}}
{{- end -}}
