{{- if .Values.redis.enabled }}
{{- range $deploymentName, $deploymentConfig := .Values.redis.deployments -}}
{{- $namespace := $deploymentConfig.namespace | default $.Values.redis.namespace -}}
{{- $redisSecret := $deploymentConfig.redisSecret | default $.Values.redis.redisSecret | default dict -}}
{{- $secretName := dig "name" "" $redisSecret -}}
{{- if $secretName }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
{{ end }}
{{ end }}
{{ end }}
