{{- if .Values.indexerStorage.enabled -}}
{{ range $storage_type, $storage_config := .Values.indexerStorage.deployments }}
{{- if and (ne false $storage_config.enabled)
           (and (hasKey $storage_config "ingress") $storage_config.ingress.enabled) -}}
{{- include "swh.ingress" (dict "Values"        $.Values
                                "serviceType"   ( print "indexer-storage-" $storage_type )
                                "configuration" $storage_config) -}}
{{- end -}}
{{ end -}}
{{- end -}}
