---
apiVersion: v1
kind: Secret
metadata:
  name: coarnotify-django-secret
type: Opaque
stringData:
  key: fake-django-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: coarnotify-db-app
type: Opaque
stringData:
  username: swh-coarnotify
  password: swh-coarnotify
  dbname: swh-coarnotify
  host: swh-coarnotify-rw
  port: "5432"
