---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kafkabackup-s3-auth
stringData:
  # DO NOT USE THESE CREDENTIALS ANYWHERE BUT IN TEST ENVIRONMENTS!
  KAFKABACKUP_S3_KEY_ID: GK50379d60fe536c2a301999c3
  KAFKABACKUP_S3_KEY_SECRET: 3b77e172f9720c905017ac265a4afd99d1f270b042c5ae77b637d3c1a398b9b8
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  name: kafkabackup-ssh-key
data:
  # associated pubkey:
  # ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLOQRrZh9DRNNbWy34AWij+guGjMv4o299VkIQdp45l kafkabackup@docker-tests
  # DO NOT USE THIS KEY ANYWHERE BUT IN TEST ENVIRONMENTS!
  ssh-privatekey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
    QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhP
    UUFBQUNBaXprRWEyWWZRMFRUVzFzdCtBRm9vL29MaG96TCtLTnZmVlpDRUhhZU9aUUFBQUpoMlZq
    UEJkbFl6CndRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWl6a0VhMllmUTBUVFcxc3QrQUZvby9v
    TGhvekwrS052ZlZaQ0VIYWVPWlEKQUFBRUIycHdTTE9waTYyeWM1Vk1tMXpqVzZaYzRhYndOZjhL
    Z0gyRWVubTIyYitDTE9RUnJaaDlEUk5OYld5MzRBV2lqKwpndUdqTXY0bzI5OVZrSVFkcDQ1bEFB
    QUFFWFJpWVhOMGFXRnVRR1Z3WldGMWRISmxBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZB
    VEUgS0VZLS0tLS0K
