---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: swh-keycloak-postgres-secret
  namespace: keycloak
  labels:
    cnpg.io/reload: "true"
stringData:
  username: keycloak
  password: keycloak