{{/* This manages non-cnpg vault static secrets for default kubernetes secrets */}}
{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.dockerCache.enabled  (ne $clusterName "local-cluster") }}
{{- $namespace := .Values.dockerCache.namespace -}}
{{- $secrets := list -}}
{{- range $instanceName, $instanceConfig := .Values.dockerCache.instances }}
  {{- if $instanceConfig.enabled }}
    {{- $instanceVars := include "swh.dockerCache.instanceVars"
                (dict "instanceName" $instanceName
                      "instanceConfig" $instanceConfig
                      "Values" $.Values) | fromYaml }}
    {{- $secretRef := $instanceVars.authenticationSecretRef -}}
    {{- if $secretRef }}
      {{- $secrets = append $secrets (list $secretRef $namespace) -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- range $secret := uniq $secrets }}
  {{ $secretName := first $secret }}
  {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{- end }}
