{{- with .Values.renovate }}
{{- if .enabled }}
{{- $secretName := .secretName -}}
{{- if $secretName }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ .namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
{{ end }}
{{- end }}
{{- end }}
