{{ if .Values.openbao.enabled }}
{{- $namespace := .Values.openbao.namespace -}}
{{- $appName := print .Values.clusterName "-openbao" -}}
{{- $version := .Values.openbao.version -}}
{{- $prune := .Values.openbao.argocdApplication.prune | default .Values.defaultPrune -}}
{{- $selfHeal := .Values.openbao.argocdApplication.selfHeal | default .Values.defaultSelfHeal -}}
{{- $logLevel := .Values.openbao.logLevel | default "info" -}}
{{- $hostIngress := .Values.openbao.hostIngress -}}
{{- $openbaoServerType := .Values.openbao.serverType | default "ha" -}}
{{- $openbaoReplicas := .Values.openbao.replicas | default 3 -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    repoURL: https://openbao.github.io/openbao-helm
    chart: openbao
    targetRevision: v{{ $version }}
    helm:
      releaseName: openbao
      values: |
        injector:
          logLevel: {{ $logLevel }}
        server:
          logLevel: {{ $logLevel }}
          {{- if eq $openbaoServerType "ha" }}
          ha:
            enabled: true
            replicas: {{ $openbaoReplicas }}
            raft:
              enabled: true
          dataStorage:
            storageClass: local-persistent
          persistentVolumeClaimRetentionPolicy:
            whenDeleted: Retain
            whenScaled: Retain
          {{- else }}
          dev:
            enabled: true
          {{- end }}
          # Enable ingress so openbao is reachable from outside the cluster too
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - host: {{ $hostIngress }}
            tls:
            - secretName: openbao-tls
              hosts:
              - {{ $hostIngress }}

  destination:
    server: {{ .Values.clusterUrl }}
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      prune: {{ $prune }}
      selfHeal: {{ $selfHeal }}
{{ end }}
