{{- if and .Values.openbao.enabled (eq .Values.clusterName "local-cluster")  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openbao-initial-secrets
  namespace: openbao
type: Opaque
stringData:
  OPENBAO_DEFAULT_TOKEN: root
{{- end }}
