---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: swh-osporadar-swh-osporadar-secret
  namespace: osporadar
  labels:
    cnpg.io/reload: "true"
stringData:
  username: osporadar
  password: osporadar
