---
apiVersion: v1
kind: Secret
metadata:
  name: swh-osporadar-secret
  namespace: osporadar
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "osporadar-django-secret-key"
  DJANGO_DB_NAME: "osporadar"
  DJANGO_DB_USER: "osporadar"
  DJANGO_DB_PASSWORD: "osporadar"
