{{- if .Values.cloudnativePg.enabled -}}
{{- range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments -}}
{{- if or (not (hasKey $clusterConfig "enabled")) (get $clusterConfig "enabled") -}}
{{- $namespace := get $clusterConfig "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- $externalClustersRef := get $clusterConfig "externalClustersRef" | default
      (get $.Values.cloudnativePg "externalClustersRef") -}}
{{- $externalPgClusters := get $.Values $externalClustersRef -}}
{{- $db_type := dig "initdb" "type" "monolith" $clusterConfig -}}
{{- $postgresqlConfig := $.Values.cloudnativePg.postgresql | default dict -}}
{{- $extraPostgresqlConfig := $clusterConfig.extraPostgresqlConfig | default dict -}}
{{- $postgresqlConfig := mustMerge $extraPostgresqlConfig $postgresqlConfig -}}
{{- $affinity := $clusterConfig.affinity | default $.Values.cloudnativePg.affinity | default dict -}}
{{- $testing := $clusterConfig.testing | default false -}}
{{- $localRoles := $clusterConfig.roles | default list -}}
{{- $globalRoles := $.Values.cloudnativePg.roles | default list -}}
{{- $roles := concat $globalRoles $localRoles -}}
{{- $storage := mustMerge ($clusterConfig.storage | default (dict)) $.Values.cloudnativePg.storage -}}
{{- $enableMonitoring := $clusterConfig.enableMonitoring | default $.Values.cloudnativePg.enableMonitoring -}}
{{- $enableSuperuserAccess := $clusterConfig.enableSuperuserAccess | default $.Values.cloudnativePg.enableSuperuserAccess -}}
{{- $delay := $clusterConfig.delay -}}
{{- $imageCatalogRef := $clusterConfig.imageCatalogRef | default $.Values.cloudnativePg.imageCatalogRef }}
{{- $walStorage := $clusterConfig.walStorage | default false -}}
{{- $services := $clusterConfig.services | default $.Values.cloudnativePg.services | default false -}}
{{- $limitedCpu := $clusterConfig.limitedCpu | default false -}}
{{- $limitedMemory := $clusterConfig.limitedMemory | default false -}}
{{- $requestedCpu := $clusterConfig.requestedCpu | default false -}}
{{- $requestedMemory := $clusterConfig.requestedMemory | default false -}}
{{- $backup := mustMerge (get $clusterConfig "backup" | default dict) ($.Values.cloudnativePg.backup | default dict) -}}
{{- $recovery := $clusterConfig.recovery | default dict -}}
{{- $database := mustMerge $clusterConfig.database ($.Values.cloudnativePg.database) | default dict -}}
{{- $dbName := required (print "Missing <$cluster_config.database.name> dbname in cluster <" $clusterName ">") $database.name -}}
{{- $dbOwner := $database.owner | default $database.name -}}
{{- $initdb := $clusterConfig.initdb | default dict -}}
{{- $superUserSecretRef := $clusterConfig.superUserSecretRef | default $.Values.cloudnativePg.superUserSecretRef -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $clusterName }}
  namespace: {{ $namespace }}
  labels:
    cnpg.io/cluster: {{ $clusterName }}
spec:
  instances: {{ $clusterConfig.instances | default 1 }}
  {{- if $superUserSecretRef }}
  superuserSecret:
    name: {{ $superUserSecretRef }}
  {{- end }}
  {{- if or $enableSuperuserAccess $superUserSecretRef }}
  enableSuperuserAccess: true
  {{- end }}
  {{- if $testing }}
  enablePDB: false
  {{- end }}
  {{- if $delay }}
  startDelay: {{ $delay }}
  stopDelay: {{ $delay }}
  {{- end }}
  {{- if $imageCatalogRef }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: {{ $imageCatalogRef }}
  {{- else }}
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  {{- end }}
  primaryUpdateStrategy: unsupervised
  {{- if $affinity }}
  affinity:
    {{- toYaml $affinity | nindent 4 }}
  {{- end }}
  {{- if $storage }}
  storage:
    {{- toYaml $storage | nindent 4 }}
  {{- end }}
  {{- if $walStorage }}
  walStorage:
    {{- toYaml $walStorage | nindent 4 }}
  {{- end }}
  {{- if $roles }}
  managed:
    roles:
    {{- toYaml $roles | nindent 4 }}
    {{- if $services }}
    services:
    {{- toYaml $services | nindent 6 }}
    {{- end }}
  {{- end }}
  {{ if or $limitedCpu $limitedMemory }}
  resources:
    requests:
      {{- if $requestedMemory }}
      memory: {{ $requestedMemory }}
      {{- end }}
      {{- if $requestedCpu }}
      cpu: {{ $requestedCpu }}
      {{- end }}
    limits:
      {{- if $limitedMemory }}
      memory: {{ $limitedMemory }}
      {{- end }}
      {{- if $limitedCpu }}
      cpu: {{ $limitedCpu }}
      {{- end }}
  {{ end }}
  {{- if $postgresqlConfig }}
  postgresql:
    {{- toYaml $postgresqlConfig | nindent 4 }}
  {{- end }}
  monitoring:
    enablePodMonitor: {{ $enableMonitoring }}
    podMonitorRelabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: instance
    podMonitorMetricRelabelings:
    - sourceLabels:
      - cluster
      targetLabel: cnpg_cluster
  bootstrap:
    {{- if and $initdb $initdb.enabled }}
    initdb:
      dataChecksums: true
      database: {{ $dbName }}
      owner: {{ $dbOwner }}
      {{- if $database.localeCollate }}
      localeCollate: {{ $database.localeCollate }}
      {{- end }}
      {{- if $database.localeCType }}
      localeCType: {{ $database.localeCType }}
      {{- end }}
      {{- if $database.secretKeyRef }}
      secret:
        name: {{ $database.secretKeyRef }}
      {{ end -}}

    {{- if $initdb.source }}
    {{- $databases := $initdb.databases | default (list $dbName) -}}
      import:
        type: microservice
        databases:
          {{- toYaml $databases | nindent 10 }}
        source:
          externalCluster: {{ $initdb.source }}
    {{- end }}
    {{- end }}
    {{- if $recovery }}
    recovery:
      database: {{ $dbName }}
      owner: {{ $dbOwner }}
      {{- toYaml $recovery | nindent 6 }}
      {{- if $database.secretKeyRef }}
      secret:
        name: {{ $database.secretKeyRef }}
      {{- end }}
    {{- end }}

  {{- if $externalPgClusters }}
  externalClusters:
    {{- toYaml $externalPgClusters | nindent 4 }}
  {{- end }}
  {{- if and $backup $backup.enabled }}
  env:
  - name: AWS_REQUEST_CHECKSUM_CALCULATION
    value: when_required
  - name: AWS_RESPONSE_CHECKSUM_VALIDATION
    value: when_required
  {{- if eq $backup.systemType "in-tree" }}
  backup:
    retentionPolicy: {{ $backup.retention | default "30d" | quote }}
    target: prefer-standby
    barmanObjectStore:
      destinationPath: {{ $backup.s3Config.path }}
      endpointURL: {{ $backup.s3Config.url }}
      s3Credentials:
        accessKeyId:
          name: {{ $backup.s3Config.secretName }}
          key: {{ $backup.s3Config.accessKey }}
        secretAccessKey:
          name: {{ $backup.s3Config.secretName }}
          key: {{ $backup.s3Config.secretKey }}
      wal:
        compression: {{ $.Values.cloudnativePg.backup.compression }}
      data:
        compression: {{ $.Values.cloudnativePg.backup.compression }}
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"
          - "-vv"
  {{- else }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: {{ $clusterName }}-objectstore
  {{ end }}
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
