{{- if .Values.cloudnativePg.enabled -}}
{{- range $cluster_name, $cluster_config := .Values.cloudnativePg.deployments -}}
{{- if or (not (hasKey $cluster_config "enabled")) (get $cluster_config "enabled") -}}
{{- $namespace := get $cluster_config "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- $externalClusterRef := get $cluster_config "externalClusterRef" | default
      (get $.Values.cloudnativePg "externalClusterRef") -}}
{{- $externalPgClusterDict := get $.Values $externalClusterRef -}}
{{- $db_type := dig "initdb" "type" "monolith" $cluster_config -}}
{{- $databases := required (print "Missing <$cluster_config.initdb.databases> value managed db in cluster <" $cluster_name ">") $cluster_config.initdb.databases -}}
{{- $config_postgresql := $cluster_config.postgresql | default $.Values.cloudnativePg.postgresql | default dict -}}
{{- $affinity := $cluster_config.affinity | default $.Values.cloudnativePg.affinity | default dict -}}
{{- $testing := $cluster_config.testing | default "false" -}}
{{- $roles := $cluster_config.roles | default $.Values.cloudnativePg.roles -}}
{{- $storage := mustMerge ($cluster_config.storage | default (dict)) $.Values.cloudnativePg.storage -}}
{{- $enableMonitoring := $cluster_config.enableMonitoring | default $.Values.cloudnativePg.enableMonitoring -}}
{{- $enableSuperuserAccess := $cluster_config.enableSuperuserAccess | default $.Values.cloudnativePg.enableSuperuserAccess -}}
{{- $delay := $cluster_config.delay -}}
{{- $imageCatalogRef := $cluster_config.imageCatalogRef }}
{{- $walStorage := $cluster_config.walStorage | default false -}}
{{- $services := $cluster_config.services | default false -}}
{{- $limitedCpu := $cluster_config.limitedCpu | default false -}}
{{- $limitedMemory := $cluster_config.limitedMemory | default false -}}
{{- $requestedCpu := $cluster_config.requestedCpu | default false -}}
{{- $requestedMemory := $cluster_config.requestedMemory | default false -}}
{{- $backup := mustMerge (get $cluster_config "backup" | default dict) ($.Values.cloudnativePg.backup | default dict) -}}
{{- $initdb := mustMerge ($cluster_config.initdb | default dict) ($.Values.cloudnativePg.initdb | default dict) -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $cluster_name }}
  namespace: {{ $namespace }}
  labels:
    cnpg.io/cluster: {{ $cluster_name }}
spec:
  instances: {{ $cluster_config.instances | default 1 }}
  {{- if $testing }}
  enablePDB: false
  {{- end }}
  {{- if $delay }}
  startDelay: {{ $delay }}
  stopDelay: {{ $delay }}
  {{- end }}
  {{- if $imageCatalogRef }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: {{ $imageCatalogRef }}
  {{- end }}
  primaryUpdateStrategy: unsupervised
  {{- if $enableSuperuserAccess }}
  enableSuperuserAccess: {{ $enableSuperuserAccess }}
  {{- end }}
  {{- if $affinity }}
  affinity:
    {{- toYaml $affinity | nindent 4 }}
  {{- end }}
  {{- if $storage }}
  storage:
    {{- toYaml $storage | nindent 4 }}
  {{- end }}
  {{- if $walStorage }}
  walStorage:
    {{- toYaml $walStorage | nindent 4 }}
  {{- end }}
  {{- if $roles }}
  managed:
    roles:
    {{- toYaml $roles | nindent 4 }}
    {{- if $services }}
    services:
    {{- toYaml $services | nindent 6 }}
    {{- end }}
  {{- end }}
  {{ if or $limitedCpu $limitedMemory }}
  resources:
    requests:
      {{- if $requestedMemory }}
      memory: {{ $requestedMemory }}
      {{- end }}
      {{- if $requestedCpu }}
      cpu: {{ $requestedCpu }}
      {{- end }}
    limits:
      {{- if $limitedMemory }}
      memory: {{ $limitedMemory }}
      {{- end }}
      {{- if $limitedCpu }}
      cpu: {{ $limitedCpu }}
      {{- end }}
  {{ end }}
  {{- if $config_postgresql }}
  postgresql:
    {{- toYaml $config_postgresql | nindent 4 }}
  {{- end }}
  monitoring:
    enablePodMonitor: {{ $enableMonitoring }}
    podMonitorMetricRelabelings:
    - sourceLabels:
      - cluster
      targetLabel: cnpg_cluster
  bootstrap:
    {{- if $initdb.secretKeyRef }}
    initdb:
      database: {{ first $databases }}
      owner: {{ first $databases }}
      dataChecksums: true
      {{- if $initdb.localeCollate }}
      localeCollate: {{ $initdb.localeCollate }}
      {{- end }}
      {{- if $initdb.localeCType }}
      localeCType: {{ $initdb.localeCType }}
      {{- end }}
      secret:
        name: {{ $initdb.secretKeyRef }}
    {{- end }}
      dataChecksums: true
      {{- if $initdb.source }}
      import:
        type: {{ $db_type }}
        databases:
          {{- toYaml $databases | nindent 10 }}
        source:
          externalCluster: {{ $initdb.source }}
      {{- end }}

  {{- if and $initdb.source $externalPgClusterDict }}
  externalClusters:
    {{- toYaml (list $externalPgClusterDict) | nindent 4 }}
  {{- end }}
  {{- if and $cluster_config.backup $cluster_config.backup.enabled }}
  backup:
    retentionPolicy: {{ $backup.retention | default "30d" | quote }}
    target: prefer-standby
    barmanObjectStore:
      destinationPath: {{ $backup.s3Config.path }}
      endpointURL: {{ $backup.s3Config.url }}
      s3Credentials:
        accessKeyId:
          name: {{ $backup.s3Config.secretName }}
          key: {{ $backup.s3Config.accessKey }}
        secretAccessKey:
          name: {{ $backup.s3Config.secretName }}
          key: {{ $backup.s3Config.secretKey }}
      wal:
        compression: {{ $.Values.cloudnativePg.backup.compression }}
      data:
        compression: {{ $.Values.cloudnativePg.backup.compression }}
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"
          - "-vv"
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
