{{ if and .Values.alerting.enabled .Values.cloudnativePg.enabled .Values.cloudnativePg.monitoringEnabled -}}
{{- range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments -}}
{{- if or (not (hasKey $clusterConfig "enabled")) (get $clusterConfig "enabled") -}}
{{- $namespace := get $clusterConfig "namespace" | default $.Values.cloudnativePg.namespace -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-queries-{{ $clusterName }}
  namespace: {{ $namespace }}
  labels:
    cnpg.io/reload: "true"
data:
  custom-queries: |
    running_queries:
      query: "SELECT datname::text, coalesce(usename::text, 'UNKNOWN') as usename, COUNT(*)::float AS count
              FROM pg_stat_activity
              WHERE NOT datname ~ '^template(0|1)$'
              GROUP BY datname, usename"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - usename:
            usage: "LABEL"
            description: "Name of the user"
        - count:
            usage: "GAUGE"
            description: "Total number of backends"

    pg_stat_activity:
      query: "SELECT
                  pg_database.datname::text,
                  states.state::text,
                  COALESCE(count, 0) as count,
                  COALESCE(max_tx_duration, 0) as max_tx_duration
              FROM
                  (VALUES ('active'),
                          ('waiting'),
                          ('idle'),
                          ('idle in transaction'),
                          ('idle in transaction (aborted)'),
                          ('fastpath function call'),
                          ('disabled')) AS states(state)
              CROSS JOIN pg_database
              LEFT JOIN
                  (SELECT
                          datname,
                          CASE WHEN state = 'active' AND wait_event_type IS NOT NULL THEN 'waiting' ELSE state END AS state,
                          count(*) AS count,
                          MAX(EXTRACT(EPOCH FROM now() - xact_start))::float AS max_tx_duration
                  FROM pg_stat_activity
                  GROUP BY 1, 2) AS act
              ON states.state = act.state AND pg_database.datname = act.datname
              WHERE NOT pg_database.datname ~ '^template(0|1)$'"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - state:
            usage: "LABEL"
            description: "State of the backend"
        - count:
            usage: "GAUGE"
            description: "Number of backends"
        - max_tx_duration:
            usage: "GAUGE"
            description: "Maximum duration of a transaction in seconds"

    settings:
      query: "SELECT
                current_setting('max_connections')::float AS max_connections,
                current_setting('autovacuum_freeze_max_age')::float AS autovacuum_freeze_max_age,
                current_setting('superuser_reserved_connections')::float AS superuser_reserved_connections,
                current_setting('max_wal_senders')::float AS max_wal_senders,
                current_setting('max_prepared_transactions')::float AS max_prepared_transactions"
      metrics:
        - max_connections:
            usage: "GAUGE"
            description: Number of connection slots reserved for superusers"
        - autovacuum_freeze_max_age:
            usage: "GAUGE"
            description: "Age at which to autovacuum a table to prevent transaction ID wraparound"
        - superuser_reserved_connections:
            usage: "GAUGE"
            description: "Number of connection slots reserved for superusers"
        - max_wal_senders:
            usage: "GAUGE"
            description: "Maximum number of simultaneously running WAL sender processes"
        - max_prepared_transactions:
            usage: "GAUGE"
            description: "Maximum number of simultaneously prepared transactions"

    pg_locks:
      query: "SELECT datname, t.mode, count(l.mode) FROM pg_database d CROSS JOIN
            (VALUES ('AccessShareLock'), ('RowShareLock'), ('RowExclusiveLock'), ('ShareUpdateExclusiveLock'), ('ShareLock'), ('ShareRowExclusiveLock'), ('ExclusiveLock'), ('AccessExclusiveLock')) t(mode)
            LEFT JOIN pg_locks l ON d.oid = l.database AND t.mode = l.mode AND l.pid <> pg_backend_pid()
            WHERE datname !~ '^template(0|1)$' GROUP BY 1, 2"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - mode:
            usage: "LABEL"
            description: "Lock type"
        - count:
            usage: "GAUGE"
            description: "Locks held"

    txid:
      query: "SELECT CASE WHEN pg_is_in_recovery() THEN 0 ELSE txid_current() END as current"
      metrics:
        - current:
            usage: "GAUGE"
            description: "Current transaction ID"

    pg_stat_database:
      query: "SELECT
                s.datname::text,
                numbackends::float,
                xact_commit::float,
                xact_rollback::float,
                blks_read::float,
                blks_hit::float,
                tup_returned::float,
                tup_fetched::float,
                tup_inserted::float,
                tup_updated::float,
                tup_deleted::float,
                conflicts::float,
                temp_files::float,
                temp_bytes::float,
                deadlocks::float,
                blk_read_time,
                blk_write_time,
                age(d.datfrozenxid) AS freeze_age,
                pg_database_size(s.datname)::float AS dbsize
              FROM pg_stat_database s
              LEFT JOIN pg_database d ON d.datname = s.datname
              WHERE NOT s.datname ~ '^template(0|1)$'"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - numbackends:
            usage: "GAUGE"
            description: "Number of backends"
        - xact_commit:
            usage: "GAUGE"
            description: ""
        - xact_rollback:
            usage: "GAUGE"
            description: ""
        - blks_read:
            usage: "GAUGE"
            description: ""
        - blks_hit:
            usage: "GAUGE"
            description: ""
        - tup_returned:
            usage: "GAUGE"
            description: ""
        - tup_fetched:
            usage: "GAUGE"
            description: ""
        - tup_inserted:
            usage: "GAUGE"
            description: ""
        - tup_updated:
            usage: "GAUGE"
            description: ""
        - tup_deleted:
            usage: "GAUGE"
            description: ""
        - conflicts:
            usage: "GAUGE"
            description: ""
        - temp_files:
            usage: "GAUGE"
            description: ""
        - temp_bytes:
            usage: "GAUGE"
            description: ""
        - deadlocks:
            usage: "GAUGE"
            description: ""
        - blk_read_time:
            usage: "GAUGE"
            description: ""
        - blk_write_time:
            usage: "GAUGE"
            description: ""
        - freeze_age:
            usage: "GAUGE"
            description: ""
        - dbsize:
            usage: "GAUGE"
            description: "Database size"

    pg_stat_user_tables:
      query: "SELECT
                current_database()::text AS datname,
                COALESCE(schemaname::text, 'null') AS schemaname,
                COALESCE(relname::text, 'null') AS relname,
                COALESCE(seq_scan, 0)::float AS seq_scan,
                COALESCE(seq_tup_read, 0)::float AS seq_tup_read,
                COALESCE(idx_scan, 0)::float AS idx_scan,
                COALESCE(idx_tup_fetch, 0)::float AS idx_tup_fetch,
                COALESCE(n_tup_ins, 0)::float AS n_tup_ins,
                COALESCE(n_tup_upd, 0)::float AS n_tup_upd,
                COALESCE(n_tup_del, 0)::float AS n_tup_del,
                COALESCE(n_tup_hot_upd, 0)::float AS n_tup_hot_upd,
                COALESCE(n_live_tup, 0)::float AS n_live_tup,
                COALESCE(n_dead_tup, 0)::float AS n_dead_tup,
                COALESCE(vacuum_count, 0)::float AS vacuum_count,
                COALESCE(autovacuum_count, 0)::float AS autovacuum_count,
                COALESCE(analyze_count, 0)::float AS analyze_count,
                COALESCE(autoanalyze_count, 0)::float AS autoanalyze_count
              FROM pg_stat_user_tables FULL JOIN (VALUES(0)) filler(i) ON TRUE
              WHERE schemaname not like 'pg_temp%'"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - schemaname:
            usage: "LABEL"
            description: "Schema name"
        - relname:
            usage: "LABEL"
            description: "Table name"
        - seq_scan:
            usage: "GAUGE"
            description: ""
        - seq_tup_read:
            usage: "GAUGE"
            description: ""
        - idx_scan:
            usage: "GAUGE"
            description: ""
        - idx_tup_fetch:
            usage: "GAUGE"
            description: ""
        - n_tup_ins:
            usage: "GAUGE"
            description: ""
        - n_tup_upd:
            usage: "GAUGE"
            description: ""
        - n_tup_del:
            usage: "GAUGE"
            description: ""
        - n_tup_hot_upd:
            usage: "GAUGE"
            description: ""
        - n_live_tup:
            usage: "GAUGE"
            description: ""
        - n_dead_tup:
            usage: "GAUGE"
            description: ""
        - vacuum_count:
            usage: "GAUGE"
            description: ""
        - autovacuum_count:
            usage: "GAUGE"
            description: ""
        - analyze_count:
            usage: "GAUGE"
            description: ""
        - autoanalyze_count:
            usage: "GAUGE"
            description: ""

    LastCheckpointDistance:
      query: "SELECT pg_wal_lsn_diff(CASE WHEN pg_is_in_recovery()
              THEN pg_last_wal_receive_lsn()
              ELSE pg_current_wal_lsn() END,
              checkpoint_lsn) \"distance\"
              FROM pg_control_checkpoint()"
      metrics:
        - distance:
            usage: "GAUGE"
            description: ""

{{ end }}
{{- end }}
{{- end }}
