{{- if and .Values.cloudnativePg.enabled (ne .Values.clusterName "local-cluster") -}}
{{ $secrets := list }}
{{ range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments }}
{{ $namespace := $clusterConfig.namespace | default $.Values.cloudnativePg.namespace }}
{{ $externalClusterRef := $clusterConfig.externalClusterRef | default $.Values.cloudnativePg.externalClusterRef | default "" }}
{{ $externalClusterConfig := get $.Values $externalClusterRef | default dict }}
{{ $externalClusterPasswordRef := dig "password" "name" "" $externalClusterConfig }}
{{ if $externalClusterPasswordRef }}
{{ $secrets = append $secrets (list $externalClusterPasswordRef $namespace) }}
{{ end }}
{{ end }}
{{ range $secret := uniq $secrets }}
{{ $secretName := first $secret }}
{{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
{{- end }}
{{- end }}
