{{- if and .Values.cloudnativePg.enabled (ne .Values.clusterName "local-cluster") -}}
  {{- $secrets := list -}}
  {{- range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments }}
    {{- $namespace := $clusterConfig.namespace | default $.Values.cloudnativePg.namespace -}}
    {{- $backupConfig := mustMerge (get $clusterConfig "backup" | default dict) ($.Values.cloudnativePg.backup | default dict) -}}
    {{/* instance can hold a super user secret */}}
    {{- $secretRef := dig "database" "secretKeyRef" "" $clusterConfig -}}
    {{- if $secretRef }}
      {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
    {{- end }}
    {{/* instance can hold a super user secret */}}
    {{- $secretRef := $clusterConfig.superUserSecretRef | default $.Values.cloudnativePg.superUserSecretRef -}}
    {{- if $secretRef }}
      {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
    {{- end }}
    {{/* backup can hold a secret */}}
    {{- if (ne false $backupConfig.enabled) }}
      {{ $secretRef := dig "s3Config" "secretName" "" $backupConfig }}
      {{- if $secretRef }}
        {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
      {{- end }}
    {{- end }}
    {{- $localRoles := $clusterConfig.roles | default list -}}
    {{- $globalRoles := $.Values.cloudnativePg.roles | default list -}}
    {{ $roles := concat $globalRoles $localRoles }}
    {{- range $role := $roles }}
      {{- $secrets = append $secrets (list $role.passwordSecret.name $namespace) -}}
    {{- end }}
  {{ end }}
  {{- range $secret := uniq $secrets }}
    {{ $secretName := first $secret }}
    {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    labels:
      cnpg.io/reload: 'true'
    name: {{ $secretName }}
    overwrite: true
    type: kubernetes.io/basic-auth
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{- end }}
