{{/* This manages non-cnpg vault static secrets for default kubernetes secrets */}}
{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.cloudnativePg.enabled (ne $clusterName "local-cluster") }}
{{- $secrets := list -}}
{{- range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments }}
  {{- $namespace := $clusterConfig.namespace | default $.Values.cloudnativePg.namespace -}}
  {{- $backupConfig := mustMerge (get $clusterConfig "backup" | default dict) ($.Values.cloudnativePg.backup | default dict) -}}
  {{/* backup can hold a secret */}}
  {{- if (ne false $backupConfig.enabled) }}
    {{- $secretRef := dig "s3Config" "secretName" "" $backupConfig -}}
    {{- if $secretRef }}
      {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
    {{- end }}
  {{- end }}
  {{- $externalClustersRef := $clusterConfig.externalClustersRef | default $.Values.cloudnativePg.externalClustersRef | default "" -}}
  {{- $externalClusterList := get $.Values $externalClustersRef | default list -}}
  {{- range $externalClusterConfig := $externalClusterList }}
    {{- $secretRef := dig "password" "name" "" $externalClusterConfig -}}
    {{- if $secretRef }}
      {{- $secrets = append $secrets (list $secretRef $namespace) -}}
    {{- end }}
    {{- $secretRef := dig "barmanObjectStore" "s3Credentials" "accessKeyId" "name" "" $externalClusterConfig -}}
    {{- if $secretRef }}
      {{- $secrets = append $secrets (list $secretRef $namespace) -}}
    {{- end }}
    {{- $secretRef := dig "barmanObjectStore" "s3Credentials" "secretAccessKey" "name" "" $externalClusterConfig -}}
    {{- if $secretRef }}
      {{- $secrets = append $secrets (list $secretRef $namespace) -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- range $secret := uniq $secrets }}
  {{ $secretName := first $secret }}
  {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{- end }}
