{{ if .Values.cloudnativePg.enabled -}}
{{- range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments -}}
{{- if or (not (hasKey $clusterConfig "enabled")) (get $clusterConfig "enabled") -}}
{{- $poolerConfig := $clusterConfig.pooler -}}
{{- if and $poolerConfig $poolerConfig.enabled -}}
{{- $namespace := get $clusterConfig "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- $poolerInstances := $poolerConfig.instances | default $clusterConfig.instances | default 1 -}}
{{- $poolMode := $poolerConfig.mode | default $.Values.cloudnativePg.pooler.mode }}
{{- $defaultPoolSize := $poolerConfig.default_pool_size | default "10" -}}
{{- $maxClientConn := $poolerConfig.max_client_conn | default "1000" -}}
{{- range $type := $poolerConfig.types -}}
{{- $name := cat $clusterName "-pooler-" $type | nospace -}}
{{- $externalLoadBalancerConfig := $poolerConfig.externalLoadBalancer | default $.Values.cloudnativePg.externalLoadBalancer -}}
{{- $externalLoadBalancer := $externalLoadBalancerConfig.enabled -}}
{{- $port := $externalLoadBalancerConfig.port | quote -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  instances: {{ $poolerInstances }}
  type: {{ $type }}
  cluster:
    name: {{ $clusterName }}
  pgbouncer:
    poolMode: {{ $poolMode }}
    parameters:
      max_client_conn: {{ $maxClientConn | quote }}
      default_pool_size: {{ $defaultPoolSize | quote }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ $name }}
            topologyKey: "kubernetes.io/hostname"
  {{- if $externalLoadBalancer }}
  serviceTemplate:
    metadata:
      labels:
        app: {{ $name }}
      annotations:
        metallb.universe.tf/allow-shared-ip: clusterIP
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      {{- if ne $port "5432" }}
      ports:
        - name: pgbouncer
          port: {{ $port }}
          targetPort: pgbouncer
          protocol: TCP
      {{- end }}
  {{- end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
