{{ if .Values.cloudnativePg.enabled -}}
{{- range $cluster_name, $cluster_config := .Values.cloudnativePg.deployments -}}
{{- if or (not (hasKey $cluster_config "enabled")) (get $cluster_config "enabled") -}}
{{- if and $cluster_config.pooler $cluster_config.pooler.enabled -}}
{{- $namespace := get $cluster_config "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- $pooler_instances := $cluster_config.pooler.instances | default $cluster_config.instances | default 1 -}}
{{- $pool_mode := $cluster_config.pooler.mode | default $.Values.cloudnativePg.pooler.mode }}
{{- $default_pool_size := $cluster_config.pooler.default_pool_size | default "10" -}}
{{- $max_client_conn := $cluster_config.pooler.max_client_conn | default "1000" -}}
{{- range $type := $cluster_config.pooler.types -}}
{{- $name := cat $cluster_name "-pooler-" $type | nospace -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  instances: {{ $pooler_instances }}
  type: {{ $type }}
  cluster:
    name: {{ $cluster_name }}
  pgbouncer:
    poolMode: {{ $pool_mode }}
    parameters:
      max_client_conn: {{ $max_client_conn | quote }}
      default_pool_size: {{ $default_pool_size | quote }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ $name }}
            topologyKey: "kubernetes.io/hostname"
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
