{{- if .Values.cloudnativePg.enabled -}}
{{- range $cluster_name, $cluster_config := .Values.cloudnativePg.deployments -}}
{{- $namespace := get $cluster_config "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- if and $cluster_config.backup $cluster_config.backup.enabled -}}
{{- $schedulePeriod := $cluster_config.backup.schedule -}}
{{- if $schedulePeriod -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-{{ $cluster_name }}
  namespace: {{ $namespace }}
spec:
  backupOwnerReference: cluster
  cluster:
    name: {{ $cluster_name }}
  immediate: true
  schedule: {{ $schedulePeriod }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
