{{- if .Values.cloudnativePg.enabled -}}
{{- range $cluster_name, $cluster_config := .Values.cloudnativePg.deployments -}}
{{- $namespace := get $cluster_config "namespace" | default $.Values.cloudnativePg.namespace -}}
{{- $backup := mustMerge (get $cluster_config "backup" | default dict) ($.Values.cloudnativePg.backup | default dict) -}}
{{- if and $backup $backup.enabled -}}
{{- $schedulePeriod := $backup.schedule -}}
{{- if $schedulePeriod -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-{{ $cluster_name }}
  namespace: {{ $namespace }}
spec:
  backupOwnerReference: cluster
  cluster:
    name: {{ $cluster_name }}
  immediate: true
  schedule: {{ $schedulePeriod }}
  {{- if eq $backup.systemType "plugin" }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
