{{- if .Values.cloudnativePg.enabled -}}
{{ $secrets := list }}
{{ range $clusterName, $clusterConfig := .Values.cloudnativePg.deployments }}
{{ $namespace := $clusterConfig.namespace | default $.Values.cloudnativePg.namespace }}
{{ $superUserSecretRef := $clusterConfig.superUserSecretRef | default $.Values.cloudnativePg.superUserSecretRef }}
{{ $secretUser := $clusterConfig.database.secretKeyRef }}
{{ $secrets = concat $secrets (list (list $secretUser $namespace) (list $superUserSecretRef $namespace)) }}
{{ $localRoles := $clusterConfig.roles | default list }}
{{ $globalRoles := $.Values.cloudnativePg.roles | default list }}
{{ $roles := concat $globalRoles $localRoles }}
{{ range $role := $roles }}
{{ $secrets = append $secrets (list $role.passwordSecret.name $namespace) }}
{{ end }}
{{ end }}
{{- range $secret := uniq $secrets -}}
{{ $secretName := first $secret }}
{{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    labels:
      cnpg.io/reload: 'true'
    name: {{ $secretName }}
    overwrite: true
    type: kubernetes.io/basic-auth
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
{{- end }}
{{- end }}
