{{/*
Generate the configuration for a remote service
*/}}
{{- define "swh.service.fromYaml" -}}
{{- $configuration := deepCopy (get .Values .configurationRef) -}}
{{- $_ := unset $configuration "secrets" -}}
{{- if .service -}}
{{- .service }}:
{{- end }}
{{ toYaml $configuration | indent 2 }}
{{- end -}}

{{/*
Create a global scheduler configuration based on scheduler section aggregation
*/}}
{{- define "swh.schedulerConfiguration" -}}
{{- $schedulerConfiguration := get .Values .configurationRef -}}
{{- if not $schedulerConfiguration -}}{{ fail (print "_helpers.yaml:swh.schedulerConfiguration: key <" .configurationRef "> is mandatory in global dict .Values")}}{{- end -}}
{{- $schedulerType := get $schedulerConfiguration "cls" -}}
{{- if eq $schedulerType "remote" -}}
{{ include "swh.service.fromYaml" (dict "service" "scheduler"
                                        "configurationRef" .configurationRef
                                        "Values" .Values) }}
{{- else if eq $schedulerType "postgresql" -}}
{{ include "swh.postgresql" (dict "serviceType" "scheduler"
                                  "Values" .Values
                                  "configurationRef" .configurationRef ) }}
{{- else -}}
{{- fail (print "_helpers.yaml:swh.schedulerConfiguration: Scheduler <" $schedulerType "> not implemented") -}}
{{- end -}}
{{- end -}}

{{/*
Generate the celery configuration. This will need evolution to deal with more celery
configuration keys.
*/}}
{{- define "celery.configuration" -}}
{{- $celeryConfiguration := get .Values .configurationRef -}}
{{- $host := required (print "_helpers.yaml:celery.configuration: The <host> property is mandatory in " $celeryConfiguration)
                    (get $celeryConfiguration "host") -}}
{{- $port := required (print "_helpers.yaml:celery.configuration: The <port> property is mandatory in " $celeryConfiguration)
                    (get $celeryConfiguration "port") -}}
{{- $user := required (print "_helpers.yaml:celery.configuration: The <user> property is mandatory in " $celeryConfiguration)
                    (get $celeryConfiguration "user") -}}
{{- $pass := required (print "_helpers.yaml:celery.configuration: The <pass> property is mandatory in " $celeryConfiguration)
                    (get $celeryConfiguration "pass") -}}
celery:
  task_broker: amqp://{{ $user }}:{{ $pass }}@{{ $host }}:{{ $port }}/%2f
{{- end -}}

{{/*
Generate the configuration for search
*/}}
{{- define "swh.search.configuration" -}}
{{- $configuration := deepCopy (get .Values .configurationRef) -}}
{{- $elasticsearchInstances := get .Values (get $configuration "elasticsearchInstancesRef") -}}
{{- $_ := unset $configuration "elasticsearchInstancesRef" -}}
{{- $_ := unset $configuration "secrets" -}}
{{ .serviceType }}:
  {{ toYaml $configuration | nindent 2 }}
  hosts:
  {{ toYaml $elasticsearchInstances | nindent 4 }}
{{- end -}}

{{/*
Generate the resolver configuration
*/}}
{{- define "swh.dns.configuration" -}}
{{- $configuration := deepCopy (get .Values .configurationRef) -}}
{{- if $configuration.policy }}
dnsPolicy: "{{ $configuration.policy }}"
{{- end }}
dnsConfig:
{{- if $configuration.ndots }}
  options:
    - name: ndots
      value: "{{ $configuration.ndots }}"
{{- end }}
{{- if $configuration.overrideSearch }}
  searches:
    - cluster.local
    - svc.cluster.local
    - {{ .Values.namespace }}.svc.cluster.local
{{- range $extraSearch := get $configuration "extraSearch" | default (list) }}
    - {{ $extraSearch }}
{{- end }}
{{- end }}
{{- if $configuration.nameservers }}
  nameservers:
  {{- range $nameserver := $configuration.nameservers }}
    - {{ $nameserver }}
  {{- end }}
{{- end }}
{{- end -}}

{{/*
   * Create an objstorage configuration based on configuration section aggregation
   */}}
{{- define "swh.objstorageConfiguration" -}}
{{- $configuration := get .Values .configurationRef -}}
{{- if not $configuration -}}
  {{ fail (print "_helper_config.yaml: swh.objstorageConfiguration: Undeclared <" .configurationRef "> storage configuration" ) }}
{{- end -}}
{{/* if no extra configurationRef is present in the configuration, the configuration
   * is simple enough, so we can apply it directly.
   * Otherwise, we may have some extra secrets and as a result an extra indirection to follow
   */}}
{{- $configurationRef := get $configuration "configurationRef" | default .configurationRef -}}
{{- $keyName := .serviceName | default "objstorage" -}}
{{- include "swh.service.fromYaml" (dict "service" $keyName
                                         "configurationRef" $configurationRef
                                         "Values" .Values) }}
{{- end -}}

