{{/*
   * Create default gunicorn configuration.
   *
*/}}
{{- define "swh.gunicorn.config" -}}
{{ $internalDefaultGunicornConfig := (dict "workers" 2 "threads" 2 "timeout" 60 ) -}}
{{ $gunicornConfig := .configuration | default .defaultConfiguration -}}
{{ mustMergeOverwrite $internalDefaultGunicornConfig $gunicornConfig | toYaml -}}
{{- end -}}

{{/*
   * Create a gunicorn logging json config file for service .serviceType
   * When the configuration is empty, this fallbacks to use the default
   * .Values.defaultLoggingConfig and .Values.rpcGunicornLoggingConfig.
   */}}
{{ define "swh.gunicorn.logging" }}
{{- $defaultConfiguration := .defaultLoggingConfig | default .Values.defaultLoggingConfig -}}
{{- $overrideConfiguration := .rpcGunicornLoggingConfig | default .Values.rpcGunicornLoggingConfig -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .serviceType }}-configuration-logging
data:
  logging-gunicorn.json: |
    {{- toPrettyJson ( mustMergeOverwrite (deepCopy $defaultConfiguration) (deepCopy $overrideConfiguration) ) | nindent 4 }}
{{- end }}

