{{- with .Values.alertmanagerConfig }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: irc-relay-config
  namespace: {{ .namespace }}
spec:
  {{- if .inhibitRules }}
  inhibitRules:
    {{- toYaml .inhibitRules | nindent 4 }}
  {{- end }}
  route:
    groupBy: ['...']
    groupWait: 31s
    groupInterval: 120s
    repeatInterval: 12h
    receiver: "null"
    continue: true
    routes:
      - receiver: "null"
        continue: false
        matchers:
        - name: "alertname"
          regex: true
          value: "InfoInhibitor|Watchdog"
      - receiver: ircrelay
  receivers:
    - name: "null"
    - name: ircrelay
      webhookConfigs:
        - sendResolved: true
          url: {{ .ircRelayHost }}
          {{ if .authentication.enabled -}}
          httpConfig:
            basicAuth:
              username:
                key: {{ .authentication.userKeyRef }}
                name: {{ .authentication.secretRef }}
              password:
                key: {{ .authentication.passwordKeyRef }}
                name: {{ .authentication.secretRef }}
          {{- end -}}
{{- end }}
{{- end }}
