{{ if .Values.storageBackfiller.enabled -}}
{{- $databaseUtilsPathChecksum := include (print $.Template.BasePath "/utils/backend-utils.yaml") . | sha256sum  -}}
{{- $configUtilsPathChecksum := include (print $.Template.BasePath "/utils/config-utils.yaml") . | sha256sum -}}
{{- range $deployment, $deploymentConfig := .Values.storageBackfiller.deployments -}}
{{- if (get $deploymentConfig "enabled") -}}
{{- $serviceType := ( print "storage-" $deployment ) -}}
{{ $last := "0xFFFFFFFFFFFFFFF" | int64 }}
{{- $first := 0 | int64 -}}
{{- $ranges := ( get $deploymentConfig "ranges" | int ) -}}
{{- $prefix := ( get $deploymentConfig "prefix" ) -}}
{{- $step := ceil (div (sub $last $first) $ranges)  -}}
{{ range $i := until $ranges }}
{{- $pos := add $first (mul $i $step) -}}
{{- $firstSwhid := printf "%s:%015x%s" $prefix $pos (repeat 25 "0") -}}
{{- $lastSwhid := printf "%s:%015x%s" $prefix (sub (add $pos $step) 1) (repeat 25 "f") }}
{{- $objectType := ( get $deploymentConfig "object_type" ) }}
{{- $name := ( print "storage-backfiller-" ( $objectType | replace "_" "-" ) "-" $deployment ) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $name }}-{{ $i }}
  labels:
    app: {{ $name }}-{{ $i }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ $name }}
      annotations:
        checksum/config: {{ include "swh.storage.configmap" (dict "serviceType" $serviceType
                                                                  "configuration" $deploymentConfig
                                                                  "Values" $.Values) | sha256sum }}
        checksum/backend-utils: {{ $databaseUtilsPathChecksum }}
        checksum/config-utils: {{ $configUtilsPathChecksum }}
    spec:
      restartPolicy: Never
      {{- if $.Values.storageBackfiller.affinity }}
      affinity:
        {{- toYaml $.Values.storageBackfiller.affinity | nindent 8 }}
      {{- end }}
      {{- if and $.Values.podPriority.enabled $.Values.storageBackfiller.priorityClassName }}
      priorityClassName: {{ $.Values.namespace }}-{{ $.Values.storageBackfiller.priorityClassName }}
      {{ end }}
      initContainers:
        - name: prepare-configuration
          image: {{ $.Values.swh_utils_image }}:{{ $.Values.storageBackfiller.swhUtilsImageVersion }}
          imagePullPolicy: IfNotPresent
          command:
          - /entrypoints/prepare-configuration.sh
          env: {{ include "swh.secrets.envFromDeploymentConfig" (dict "Values" $.Values "deploymentConfig" $deploymentConfig) | nindent 10 }}
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
          - name: configuration-template
            mountPath: /etc/swh/configuration-template
          - name: config-utils
            mountPath: /entrypoints
            readOnly: true
        {{- if $deploymentConfig.checkDbVersion }}
        {{ include "swh.checkDatabaseVersionContainer" (dict "Values" $.Values
                                                             "imagePrefixName" "swh_storage_image"
                                                             "module" "storage"
                                                             "imageVersion" $.Values.storageBackfiller.imageVersion ) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ get $deploymentConfig "object_type" | replace "_" "-" }}-{{ $deployment }}
          image: {{ $.Values.swh_storage_image }}:{{ $.Values.storageBackfiller.imageVersion }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: {{ $deploymentConfig.requestedMemory | default "512Mi" }}
              cpu: {{ $deploymentConfig.requestedCpu | default "500m" }}
            {{- if or $deploymentConfig.limitedMemory $deploymentConfig.limitedCpu }}
            limits:
              {{- if $deploymentConfig.limitedMemory }}
              memory: {{ $deploymentConfig.limitedMemory }}
              {{- end }}
              {{- if $deploymentConfig.limitedCpu }}
              cpu: {{ $deploymentConfig.limitedCpu }}
              {{- end }}
            {{- end }}
          command:
          - /opt/swh/entrypoint.sh
          args:
          - swh
          - storage
          - -C
          - /etc/swh/config.yml
          - backfill
          - --start-object
          - {{ $firstSwhid }}
          - --end-object
          - {{ $lastSwhid }}
          - {{ $objectType }}
          env:
            - name: STATSD_HOST
              value: {{ $.Values.statsdExternalHost | default "prometheus-statsd-exporter" }}
            - name: STATSD_PORT
              value: {{ $.Values.statsdPort | default "9125" | quote }}
            - name: STATSD_TAGS
              value: deployment:{{ $name }}
            - name: SWH_LOG_LEVEL
              value: {{ $deploymentConfig.logLevel | default $.Values.storage.logLevel | quote }}
          {{- if $.Values.storage.sentry.enabled }}
            - name: SWH_SENTRY_ENVIRONMENT
              value: {{ $.Values.sentry.environment }}
            - name: SWH_MAIN_PACKAGE
              value: swh.storage
            - name: SWH_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.storage.sentry.secretKeyRef }}
                  key: {{ $.Values.storage.sentry.secretKeyName }}
                  # 'name' secret should exist & include key
                  # if the setting doesn't exist, sentry pushes will be disabled
                  optional: true
            - name: SWH_SENTRY_DISABLE_LOGGING_EVENTS
              value: "true"
          {{- end }}
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
      volumes:
      - name: configuration
        emptyDir: {}
      - name: configuration-template
        configMap:
          name: {{ $name }}-configuration-template
          items:
          - key: "config.yml.template"
            path: "config.yml.template"
      - name: backend-utils
        configMap:
          name: backend-utils
          defaultMode: 0555
      - name: config-utils
        configMap:
          name: config-utils
          defaultMode: 0555
{{ $pos := add $pos $step -}}
{{ end }}
{{ end }}
{{ end }}
{{- end }}
