{{ if .Values.storageBackfiller.enabled -}}
{{ range $deployment, $deploymentConfig := .Values.storageBackfiller.deployments }}
{{- if (get $deploymentConfig "enabled") -}}
{{- $objectType := ( get $deploymentConfig "object_type" | replace "_" "-" ) }}
{{- $serviceType := ( print "storage-backfiller-" $objectType "-" $deployment ) }}
{{ include "swh.backfiller.configmap" (dict "serviceType" $serviceType
                                         "configuration" $deploymentConfig
                                         "Values" $.Values) }}
{{- end -}}
{{ end -}}
{{- end -}}
