{{ if .Values.victorialogs.enabled -}}
{{- $appName := print .Values.clusterName "-vl" -}}
{{- $storageVolumes := .Values.victorialogs.storage.volumes }}
{{- $selectIngress := .Values.victorialogs.select.ingress }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  revisionHistoryLimit: 2
  project: {{ .Values.defaultProject }}
  source:
    chart: victoria-logs-cluster
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: {{ .Values.victorialogs.version }}
    helm:
      # must match the application name (https://github.com/argoproj/argo-cd/issues/2871)
      releaseName: {{ $appName }}
      values: |
        vlinsert:
          fullnameOverride: {{ .Values.victorialogs.insert.name }}
        vlselect:
          fullnameOverride: {{ .Values.victorialogs.select.name }}
          {{- if $selectIngress.enabled }}
          ingress:
            enabled: true
            hosts:
              - name: {{ $selectIngress.host }}
                path:
                  - /select
            ingressClassName: nginx
            {{- if $selectIngress.annotations }}
            annotations:
              {{- toYaml $selectIngress.annotations | nindent 14 }}
            {{- end }}
            {{- if $selectIngress.tls }}
            tls:
            - secretName: victorialogs-tls
              hosts:
              - {{ $selectIngress.host }}
            {{- end }}
          {{- end }}
        vlstorage:
          fullnameOverride: {{ .Values.victorialogs.storage.name }}
          retentionPeriod: {{ .Values.victorialogs.storage.retentionPeriod }}
          replicaCount: {{ .Values.victorialogs.storage.replicaCount }}
          persistentVolume:
            size: {{ $storageVolumes.size }}
            {{- if $storageVolumes.className }}
            storageClassName: {{ $storageVolumes.className }}
            {{- end }}
        vmauth:
          enabled: {{ .Values.victorialogs.vmauth.enabled }}
  destination:
    server: {{ .Values.clusterUrl }}
    namespace: {{ .Values.victorialogs.namespace | quote }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: {{ .Values.defaultPrune }}
      selfHeal: {{ .Values.defaultSelfHeal }}
{{ end }}
