{{- if .Values.dataportal.enabled }}
{{- $appName := print .Values.clusterName "-dataportal" -}}
{{- $namespace := .Values.dataportal.namespace -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - name: swh-dataportal
          image: "{{ .Values.dataportal.image.repository }}:{{ .Values.dataportal.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80

{{- end }}