{{- if .Values.rabbitmq.enabled -}}
{{- range $deployment_name, $deployment_config := .Values.rabbitmq.deployments -}}
{{- if or (not (hasKey $deployment_config "enabled")) (get $deployment_config "enabled") -}}
{{- $clusterName := print "rabbitmq-" $deployment_name -}}
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: celeryev
  namespace: {{ $deployment_config.namespace | default $.Values.rabbitmq.namespace }}
spec:
  name: celeryev
  vhost: "/"
  type: topic
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: {{ $clusterName }}

{{ end }}
{{ end }}
{{- end -}}
