{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.rabbitmq.enabled (ne $clusterName "local-cluster") }}
{{- range $deploymentName, $deploymentConfig := .Values.rabbitmq.deployments -}}
{{- $namespace := $deploymentConfig.namespace | default $.Values.rabbitmq.namespace -}}
{{- $secretName := $deploymentConfig.secretRef | default $.Values.rabbitmq.secretRef | default (print $deploymentName "-secret") -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
{{ end }}
{{ end }}
