{{ if .Values.provenance.enabled -}}
{{ range $provenanceType, $deploymentConfig := .Values.provenance.deployments }}
{{- $serviceType := ( print "provenance-" $provenanceType ) -}}
{{- if or (not (hasKey $deploymentConfig "enabled")) (get $deploymentConfig "enabled") }}
{{- if and (hasKey $deploymentConfig "ingress") $deploymentConfig.ingress.enabled -}}

{{- $configuration := include "swh.provenance.config" (dict "configuration" $deploymentConfig
                                                            "Values" $.Values) | fromYaml -}}
{{- include "swh.ingress" (dict "serviceType"   $serviceType
                                "configuration" $configuration
                                "Values"        $.Values) -}}
{{- end -}}
{{- if $deploymentConfig.extraIngresses -}}
{{ $extraNameLabelCtr := 0 }}
{{ range $extraIngressConfig := $deploymentConfig.extraIngresses }}
{{ $extraNameLabelCtr = add $extraNameLabelCtr 1 }}
{{- $mergedIngressConfig :=
  mustMergeOverwrite (omit $deploymentConfig "extraIngresses" "ingress")
                     (dict "ingress" (mustMergeOverwrite $deploymentConfig.ingress $extraIngressConfig)) -}}
{{- $config := include "swh.provenance.config" (dict "configuration" $mergedIngressConfig
                                                     "Values" $.Values) | fromYaml -}}
{{- include "swh.ingress" (dict "serviceType"    $serviceType
                                "configuration"  $config
                                "extraNameLabel" ( print "extra-" $extraNameLabelCtr )
                                "Values"         $.Values) -}}
{{- end -}}
{{- end -}}

{{ end -}}
{{- end -}}
{{- end -}}

