{{ if .Values.loaderMetadata.enabled -}}
{{ $journalClientConfigurationRef := .Values.loaderMetadata.journalClientConfigurationRef }}
{{ $journalClientOverrides := deepCopy (get .Values.loaderMetadata "journalClientOverrides" | default dict) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loader-metadata-template
  namespace: {{ .Values.namespace }}
data:
  config.yml.template: |
    {{- include "swh.storageConfiguration" (dict "configurationRef" .Values.loaderMetadata.storageConfigurationRef
                                                 "Values" .Values) | nindent 4 }}

    {{- include "swh.schedulerConfiguration" (dict "configurationRef" .Values.loaderMetadata.schedulerConfigurationRef
                                                   "Values" .Values) | nindent 4 }}

    {{- include "swh.journalClientConfiguration"
                  (dict "serviceType" "journal"
                        "configurationRef" $journalClientConfigurationRef
                        "overrides" $journalClientOverrides
                        "Values" .Values) | nindent 4 }}
    reload_after_days: {{ .Values.loaderMetadata.reload_after_days | default 120 }}
    metadata_fetcher_credentials:

  init-container-entrypoint.sh: |
    #!/bin/bash

    set -e

    CONFIG_FILE=/etc/swh/config.yml

    # substitute environment variables when creating the default config.yml
    eval echo \""$(</etc/swh/configuration-template/config.yml.template)"\" \
      > $CONFIG_FILE

    CREDS_PATH=/etc/credentials/metadata-fetcher/credentials
    [ -f $CREDS_PATH ] && \
      sed 's/^/  /g' $CREDS_PATH >> $CONFIG_FILE

    exit 0
{{ end }}
