{{/*
   * Create a configuration dict for specific dataset export instance.
   *
   * This raises as soon as a missing key is detected.
   */}}
{{- define "swh.datasets.generator.config" -}}
{{- $config := deepCopy .datasetGeneratorConfiguration -}}
{{- $topLevelConfig := .datasetsGeneratorConfiguration -}}
{{- $datasetsConfig := $topLevelConfig.datasets -}}

{{- $logLevel := $config.logLevel | default $datasetsConfig.logLevel | default $topLevelConfig.logLevel -}}
{{- $namespace := $config.namespace | default $datasetsConfig.namespace | default $topLevelConfig.namespace | default .Values.namespace -}}
{{- $replicas := $config.replicas | default $datasetsConfig.replicas | default 1 -}}
{{- $affinity := $config.affinity | default $datasetsConfig.affinity | default dict -}}
{{- $priorityClassName := $config.priorityClassName | default $datasetsConfig.priorityClassName -}}
{{- $nbProcesses := $config.nbProcesses | default 1 -}}
{{- $datasetGeneratorTask := required (print "Required dataset export type (a luigi task name)") $config.generatorTask -}}
{{- $urlRef := $config.luigiSchedulerUrlRef | default $datasetsConfig.luigiSchedulerUrlRef -}}
{{- $luigiSchedulerUrlRef := required (print "Required luigi scheduler url reference.") $urlRef -}}
{{- $luigiSchedulerUrl := required (print "Invalid <luigiSchedulerUrlRef> configuration key.") (get .Values $luigiSchedulerUrlRef) -}}
{{- $graphPathRef := $config.graphDirectoryPathRef | default $datasetsConfig.graphDirectoryPathRef -}}
{{- $graphDirectoryPathRef := required (print "Required graph directory path reference.") $graphPathRef -}}
{{- $graphDirectoryPath := required (print "Invalid <graphDirectoryPathRef> configuration key.") (get .Values $graphDirectoryPathRef) -}}
{{- $requestedMemory := $config.requestedMemory | default $topLevelConfig.requestedMemory | default $datasetsConfig.requestedMemory | default "512Mi" -}}
{{- $requestedCpu := $config.requestedCpu | default $topLevelConfig.requestedCpu | default $datasetsConfig.requestedCpu | default "500m" -}}
{{- $limitedMemory := $config.limitedMemory | default $topLevelConfig.limitedMemory | default $datasetsConfig.limitedMemory -}}
{{- $limitedCpu := $config.limitedCpu | default $topLevelConfig.limitedCpu | default $datasetsConfig.limitedCpu -}}
{{- $configPath := "/etc/swh/config.yml" -}}
{{- $debug := $config.debug | default $topLevelConfig.debug | default false -}}

{{- dict "serviceType"          (print "dataset-" .datasetGeneratorName)
         "logLevel"             $logLevel
         "namespace"            $namespace
         "replicas"             $replicas
         "affinity"             $affinity
         "priorityClassName"    $priorityClassName
         "luigiSchedulerUrl"    $luigiSchedulerUrl
         "graphDirectoryDir"    $graphDirectoryPath
         "datasetGeneratorTask" $datasetGeneratorTask
         "configPath"           $configPath
         "nbProcesses"          $nbProcesses
         "requestedMemory"      $requestedMemory
         "requestedCpu"         $requestedCpu
         "limitedMemory"        $limitedMemory
         "limitedCpu"           $limitedCpu
         "debug"                $debug | mustMergeOverwrite $config | toYaml -}}
{{- end -}}
