{{/*
   * Create a configuration dict for specific dataset export instance.
   *
   * This raises as soon as a missing key is detected.
   */}}
{{- define "swh.datasets.generator.config" -}}
{{- $config := deepCopy .datasetGeneratorConfiguration -}}
{{- $topLevelConfig := .datasetsGeneratorConfiguration -}}
{{- $datasetsConfig := $topLevelConfig.datasets -}}

{{- $logLevel := $config.logLevel | default $datasetsConfig.logLevel | default $topLevelConfig.logLevel | upper | quote -}}
{{- $namespace := $config.namespace | default $datasetsConfig.namespace | default $topLevelConfig.namespace | default .Values.namespace -}}
{{- $replicas := $config.replicas | default $datasetsConfig.replicas | default 1 -}}
{{- $affinity := $config.affinity | default $datasetsConfig.affinity | default dict -}}
{{- $priorityClassName := $config.priorityClassName | default $datasetsConfig.priorityClassName -}}
{{- $nbProcesses := $config.nbProcesses | default $datasetsConfig.nbProcesses | default 1 -}}
{{- $nbWorkers := $config.nbWorkers | default $datasetsConfig.nbWorkers | default 1 -}}
{{- $urlRef := $config.luigiSchedulerUrlRef | default $datasetsConfig.luigiSchedulerUrlRef -}}
{{- $luigiSchedulerUrlRef := required (print "Required luigi scheduler url reference.") $urlRef -}}
{{- $luigiSchedulerUrl := required (print "Invalid <luigiSchedulerUrlRef> configuration key.") (get .Values $luigiSchedulerUrlRef) -}}
{{- $graphPathRef := $config.graphDirectoryPathRef | default $datasetsConfig.graphDirectoryPathRef -}}
{{- $graphDirectoryPathRef := required (print "Required graph directory path reference.") $graphPathRef -}}
{{- $graphMountpoint := required (print "Invalid <graphDirectoryPathRef> configuration key.") (get .Values $graphDirectoryPathRef) -}}
{{- $graphDirectoryPath := print $graphMountpoint "/" .datasetGeneratorName -}}
{{- $graphSensitiveMountpoint :=  print $graphMountpoint "-sensitive" -}}
{{- $graphSensitiveDirectoryPath := print $graphSensitiveMountpoint "/" .datasetGeneratorName -}}
{{- $datasetsChecks := $config.checks | default $datasetsConfig.checks -}}
{{- $graphCheckFlavor := $datasetsChecks.enabled | ternary $datasetsChecks.name "none" -}}
{{- $requestedMemory := $config.requestedMemory | default $topLevelConfig.requestedMemory | default $datasetsConfig.requestedMemory | default "512Mi" -}}
{{- $requestedCpu := $config.requestedCpu | default $topLevelConfig.requestedCpu | default $datasetsConfig.requestedCpu | default "500m" -}}
{{- $limitedMemory := $config.limitedMemory | default $topLevelConfig.limitedMemory | default $datasetsConfig.limitedMemory -}}
{{- $limitedCpu := $config.limitedCpu | default $topLevelConfig.limitedCpu | default $datasetsConfig.limitedCpu -}}
{{- $configPath := "/etc/swh/config.yml" -}}
{{- $toolbox := $config.toolbox | default $topLevelConfig.toolbox | default false -}}
{{- $imageVersion := $config.imageVersion | default $datasetsConfig.imageVersion | default $topLevelConfig.imageVersion | default .Values.swh_datasets_image_version -}}
{{- $batchSize := $config.batchSize | default $datasetsConfig.batchSize -}}
{{- $sensitiveDataMixed := $config.sensitiveDataMixed | default $datasetsConfig.sensitiveDataMixed -}}
{{- $publish := $config.publish | default $datasetsConfig.publish -}}
{{- $publish := and $publish (not $sensitiveDataMixed) -}}
{{- dict "serviceType"       (print "dataset-" .datasetGeneratorName)
         "logLevel"          $logLevel
         "namespace"         $namespace
         "replicas"          $replicas
         "affinity"          $affinity
         "priorityClassName" $priorityClassName
         "luigiSchedulerUrl" $luigiSchedulerUrl
         "graphMountpoint"   $graphMountpoint
         "graphDirectoryPath" $graphDirectoryPath
         "graphSensitiveMountpoint" $graphSensitiveMountpoint
         "graphSensitiveDirectoryPath" $graphSensitiveDirectoryPath
         "graphCheckFlavor"  $graphCheckFlavor
         "configPath"        $configPath
         "nbProcesses"       $nbProcesses
         "nbWorkers"         $nbWorkers
         "batchSize"         $batchSize
         "sensitiveDataMixed" $sensitiveDataMixed
         "publish"           $publish
         "requestedMemory"   $requestedMemory
         "requestedCpu"      $requestedCpu
         "limitedMemory"     $limitedMemory
         "limitedCpu"        $limitedCpu
         "imageVersion"      $imageVersion
         "toolbox"           $toolbox | mustMergeOverwrite $config | toYaml -}}
{{- end -}}
