{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $datasetsConfig := $datasetsGeneratorConfig.datasets -}}
{{- if or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled") -}}
{{- $configChecksum := include (print $.Template.BasePath "/datasets-generator/datasets-configmap.yaml") . | sha256sum -}}
{{- $configScriptUtilsChecksum := include (print $.Template.BasePath "/datasets-generator/datasets-script-utils.yaml") . | sha256sum -}}
{{- $containerImage := .Values.swh_datasets_image -}}

{{- range $datasetGeneratorName, $datasetGeneratorConfig := $datasetsGeneratorConfig.datasets.deployments -}}
{{- if or (not (hasKey $datasetGeneratorConfig "enabled")) (get $datasetGeneratorConfig "enabled") -}}
{{- $config := include "swh.datasets.generator.config"
      (dict "datasetGeneratorName"           $datasetGeneratorName
            "datasetGeneratorConfiguration"  $datasetGeneratorConfig
            "datasetsGeneratorConfiguration" $datasetsGeneratorConfig
            "Values"                         $.Values) | fromYaml -}}
{{- $toolbox := $config.toolbox -}}
{{- $graphMountpoint := $config.graphMountpoint -}}
{{- $graphDirectoryPath := $config.graphDirectoryPath -}}
{{- $graphSensitiveMountpoint := $config.graphSensitiveMountpoint -}}
{{- $graphSensitiveDirectoryPath := $config.graphSensitiveDirectoryPath -}}
{{- $batchSize := $config.batchSize -}}
{{- $sensitiveDataMixed := $config.sensitiveDataMixed -}}
{{- $publish := $config.publish -}}
{{- $logLevel := $config.logLevel -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $config.namespace }}
  name: {{ $config.serviceType }}
  labels:
    app: {{ $config.serviceType }}
spec:
  revisionHistoryLimit: 2
  {{ if $config.replicas }}
  replicas: {{ $config.replicas }}
  {{ end -}}
  selector:
    matchLabels:
      app: {{ $config.serviceType }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $config.serviceType }}
      annotations:
        checksum/config: {{ $configChecksum }}
        checksum/script-utils: {{ $configScriptUtilsChecksum }}
    spec:
      hostname: {{ $config.serviceType }}
      {{- if $config.affinity }}
      affinity:
        {{- toYaml $config.affinity | nindent 8 }}
      {{- end }}
      {{- if and $.Values.podPriority.enabled $config.priorityClassName }}
      priorityClassName: {{ print $config.namespace "-" $config.priorityClassName | quote }}
      {{ end }}
      initContainers:
        - name: {{ $config.serviceType }}-prepare-configuration
          image: {{ $.Values.swh_utils_image }}:{{ $.Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          command:
          - /entrypoints/prepare-configuration.sh
          env: {{ include "swh.secrets.envFromDeploymentConfig"
                  (dict "deploymentConfig" $datasetsGeneratorConfig
                        "Values" $.Values) | nindent 12 }}
          volumeMounts:
          - name: dataset-configuration
            mountPath: /etc/swh
          - name: config-{{ $config.serviceType }}-template
            mountPath: /etc/swh/configuration-template
          - name: config-utils
            mountPath: /entrypoints
            readOnly: true
        {{- if $publish }}
        - name: datasets-config-{{ $config.serviceType }}-prepare-configuration
          image: {{ $.Values.swh_utils_image }}:{{ $.Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          command:
          - /entrypoints/prepare-configuration.sh
          env: {{ include "swh.secrets.envFromDeploymentConfig"
                  (dict "deploymentConfig" $datasetsGeneratorConfig
                        "Values" $.Values) | nindent 12 }}
            - name: CONFIG_TEMPLATE_PATH
              value: /opt/swh/.aws/configuration-template/aws-config.template
            - name: CONFIG_PATH
              value: /opt/swh/.aws/config
          volumeMounts:
          - name: publish-configuration
            mountPath: /opt/swh/.aws
          - name: publish-{{ $config.serviceType }}-template
            mountPath: /opt/swh/.aws/configuration-template
          - name: datasets-config-utils
            mountPath: /entrypoints
            readOnly: true
        {{- end }}

      containers:
        - name: {{ $config.serviceType }}
          resources:
            requests:
              memory: {{ $config.requestedMemory }}
              cpu: {{ $config.requestedCpu }}
          {{- if or $config.limitedMemory $config.limitedCpu }}
            limits:
            {{- if $config.limitedMemory }}
              memory: {{ $config.limitedMemory }}
            {{- end }}
            {{- if $config.limitedCpu }}
              cpu: {{ $config.limitedCpu }}
            {{- end }}
          {{- end }}
          image: {{ print $containerImage ":" $config.imageVersion | quote }}
          imagePullPolicy: IfNotPresent
          {{- if $toolbox }}
          command:
          - /bin/sleep
          args:
          - infinity
          {{- else }}
          command:
          - /script/generate-and-publish-compressed-graph-dataset.sh
          {{ end }}
          env:
            {{- if eq $logLevel (quote "DEBUG") }}
            - name: SWH_DEBUG_ENTRYPOINT
              value: "1"
            {{- end }}
            - name: GRAPH_MOUNTPOINT
              value: {{ $graphMountpoint | quote }}
            - name: GRAPH_DIRECTORY_PATH
              value: {{ $graphDirectoryPath | quote }}
            {{- if not $sensitiveDataMixed }}
            - name: GRAPH_SENSITIVE_MOUNTPOINT
              value: {{ $graphSensitiveMountpoint | quote }}
            - name: GRAPH_SENSITIVE_DIRECTORY_PATH
              value: {{ $graphSensitiveDirectoryPath | quote }}
            {{- end }}
            - name: GRAPH_DATASET_NAME
              value: {{ $datasetGeneratorName | quote }}
            - name: GRAPH_COMPRESSED_DIRECTORY_PATH
              value: {{ print $graphDirectoryPath "/compressed" | quote }}
            - name: LUIGI_SCHEDULER_URL
              value: {{ $config.luigiSchedulerUrl | quote }}
            - name: SWH_CONFIG_FILENAME
              value: /etc/swh/config.yml
            - name: NB_PROCESSES
              value: {{ $config.nbProcesses | quote }}
            - name: NB_WORKERS
              value: {{ $config.nbWorkers | quote }}
            - name: LOG_LEVEL
              value: {{ $logLevel }}
            - name: GRAPH_CHECK_FLAVOR
              value: {{ $config.graphCheckFlavor }}
            {{- if $batchSize }}
            - name: BATCH_SIZE
              value: {{ $batchSize | int | quote }}
            {{- end }}
            {{- if $publish }}
            - name: PUBLISH
              value: "1"
            {{ include "swh.secrets.envFromDeploymentConfig"
              (dict "deploymentConfig" $datasetsGeneratorConfig
                    "Values" $.Values) | nindent 12 }}
            {{- end }}
          volumeMounts:
          - name: dataset-configuration
            mountPath: /etc/swh
          {{- if $publish }}
          - name: publish-configuration
            mountPath: /opt/swh/.aws
          {{- end }}
          - name: datasets-script-utils
            mountPath: /script
          {{- range $volumeName, $volumeConfig := $datasetGeneratorConfig.extraVolumes }}
          {{ $mountPath := eq "sensitive" $volumeName | ternary $graphSensitiveDirectoryPath $graphDirectoryPath }}
          - name: {{ $volumeName }}
            mountPath: {{ $volumeConfig.mountPath | default $mountPath }}
            readOnly: {{ $volumeConfig.readOnly | default "false" }}
          {{- end }}
      volumes:
      - name: dataset-configuration
        emptyDir: {}
      - name: config-{{ $config.serviceType }}-template
        configMap:
          name: config-{{ $config.serviceType }}-template
          items:
          - key: "config.yml.template"
            path: "config.yml.template"
      - name: datasets-script-utils
        configMap:
          name: datasets-script-utils
          defaultMode: 0555
      - name: config-utils
        configMap:
          name: config-utils
          defaultMode: 0555
      {{- if $publish }}
      - name: publish-configuration
        emptyDir: {}
      - name: publish-{{ $config.serviceType }}-template
        configMap:
          name: publish-{{ $config.serviceType }}-template
          items:
          - key: "aws-config.template"
            path: "aws-config.template"
      - name: datasets-config-utils
        configMap:
          name: datasets-config-utils
          defaultMode: 0555
      {{- end }}
      {{- range $volumeName, $volumeConfig := $datasetGeneratorConfig.extraVolumes }}
      - name: {{ $volumeName }}
        {{- toYaml $volumeConfig.volumeDefinition | nindent 8 }}
      {{ end }}
{{ end }}
{{ end }}
{{ end }}
