{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $datasetsConfig := $datasetsGeneratorConfig.datasets -}}
{{- if or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled") -}}
{{- range $datasetGeneratorName, $datasetGeneratorConfig := $datasetsConfig.deployments -}}
{{- if or (not (hasKey $datasetGeneratorConfig "enabled")) (get $datasetGeneratorConfig "enabled") -}}
{{- $config := include "swh.datasets.generator.config"
      (dict "datasetGeneratorName"           $datasetGeneratorName
            "datasetGeneratorConfiguration"  $datasetGeneratorConfig
            "datasetsGeneratorConfiguration" $datasetsGeneratorConfig
            "Values"                         $.Values) | fromYaml -}}

{{- $journalConfigRef := $datasetsGeneratorConfig.journalClientConfigurationRef | default $datasetsConfig.journalClientConfigurationRef -}}
{{- $journalConfigurationRef := required (print "Mandatory key <journalConfigurationRef> missing.") $journalConfigRef -}}
{{- $maskingDbConfigRef := $datasetGeneratorConfig.maskingDbConfigurationRef | default $datasetsConfig.maskingDbConfigurationRef -}}
{{- $maskingDbConfigurationRef := required (print "Mandatory key <maskingDbConfigurationRef> missing.") $maskingDbConfigRef -}}
{{- $connstring := include "swh.connstring" (dict "configurationRef" $maskingDbConfigurationRef
                                                  "Values" $.Values) -}}
{{- $graphSensitiveDirectoryPath := $config.graphSensitiveDirectoryPath -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ $config.serviceType }}-template
  namespace: {{ $config.namespace }}
data:
  config.yml.template: |
    {{- include "swh.journalClientConfiguration" (dict "configurationRef" $journalConfigurationRef
                                                       "Values" $.Values) | nindent 4 }}
    masking_db: {{ $connstring }}
{{ end }}
{{ end }}
{{ end }}
