{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $schedulerConfig := $datasetsGeneratorConfig.scheduler -}}

{{- if or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled") -}}
{{- $namespace := $datasetsGeneratorConfig.namespace | default .Values.namespace -}}
{{- $logLevel := $datasetsGeneratorConfig.logLevel | default "INFO" -}}

{{- include "swh.datasets.config.luigi" (dict "schedulerConfig" $schedulerConfig
                                              "configmapName"   "datasets-luigi-configmap-configuration-template"
                                              "namespace"       $namespace
                                              "logLevel"        $logLevel) -}}
{{- end -}}
