{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $datasetsConfig := $datasetsGeneratorConfig.datasets -}}
{{- if or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasets-script-utils
  namespace: {{ .Values.namespace }}
data:
  cleanup-generated-compressed-graph.sh: |
    #!/usr/bin/env bash
    # Uses env variables:
    # - GRAPH_DIRECTORY_PATH
    # Uses optional env variables:
    # - GRAPH_SENSITIVE_DIRECTORY_PATH
    set -e

    if [ -n "${SWH_DEBUG_ENTRYPOINT}" ]; then
        set -x
    fi

    [ -z "${GRAPH_DIRECTORY_PATH}" ] && \
      echo "<GRAPH_DIRECTORY_PATH> env variable must be set" && exit 1

    rm -rf "${GRAPH_DIRECTORY_PATH}"/{.*,*} && \
      echo "Cleanup <${GRAPH_DIRECTORY_PATH}> done"

    if [ -n "${GRAPH_SENSITIVE_DIRECTORY_PATH}" ]; then
      rm -rf "${GRAPH_SENSITIVE_DIRECTORY_PATH}"/{.*,*} && \
        echo "Cleanup <${GRAPH_SENSITIVE_DIRECTORY_PATH}> done"
    fi

  display-compressed-graph-logs.sh: |
    #!/usr/bin/env bash
    # Uses env variables:
    # - GRAPH_COMPRESSED_DIRECTORY_PATH
    set -e

    [ -z "${GRAPH_COMPRESSED_DIRECTORY_PATH}" ] && \
      echo "<GRAPH_COMPRESSED_DIRECTORY_PATH> env variable must be set" && exit 1

    for logpath in $(ls "${GRAPH_COMPRESSED_DIRECTORY_PATH}"/logs/*); do
      echo "##################### ${logpath}"
      cat "${logpath}"
      echo
    done

  generate-compressed-graph.sh: |
    #!/usr/bin/env bash
    # Uses mandatory env variables:
    # - SWH_CONFIG_FILENAME
    # - LUIGI_SCHEDULER_URL
    # - GRAPH_MOUNTPOINT
    # - GRAPH_DATASET_NAME
    # - NB_PROCESSES
    # - LOG_LEVEL
    # Uses optional env variables:
    # - SWH_DEBUG_ENTRYPOINT
    # - BATCH_SIZE
    # - GRAPH_SENSITIVE_MOUNTPOINT

    set -e

    if [ -n "${SWH_DEBUG_ENTRYPOINT}" ]; then
        set -x
    fi

    [ -z "${SWH_CONFIG_FILENAME}" ] && \
      echo "<SWH_CONFIG_FILENAME> env variable must be set" && exit 1
    [ -z "${LUIGI_SCHEDULER_URL}" ] && \
      echo "<LUIGI_SCHEDULER_URL> env variable must be set" && exit 1
    [ -z "${GRAPH_MOUNTPOINT}" ] && \
      echo "<GRAPH_MOUNTPOINT> env variable must be set" && exit 1
    [ -z "${GRAPH_DATASET_NAME}" ] && \
      echo "<GRAPH_DATASET_NAME> env variable must be set" && exit 1
    [ -z "${NB_PROCESSES}" ] && \
      echo "<NB_PROCESSES> env variable must be set" && exit 1
    [ -z "${LOG_LEVEL}" ] && \
      echo "<LOG_LEVEL> env variable must be set" && exit 1

    EXTRA_CLI_FLAGS=()
    if [ -n "${BATCH_SIZE}" ]; then
      EXTRA_CLI_FLAGS+=('--batch-size' "${BATCH_SIZE}")
    fi

    if [ -n "${GRAPH_SENSITIVE_MOUNTPOINT}" ]; then
      EXTRA_CLI_FLAGS+=('--base-sensitive-directory' "${GRAPH_SENSITIVE_MOUNTPOINT}")
    fi

    set -x

    /opt/swh/entrypoint.sh \
       swh datasets luigi \
          --dataset-name "${GRAPH_DATASET_NAME}" \
          --base-directory "${GRAPH_MOUNTPOINT}" \
          "${EXTRA_CLI_FLAGS[@]}" \
          CompressGraph \
          -- \
          --scheduler-url "${LUIGI_SCHEDULER_URL}" \
          --ExportGraph-export-name "${GRAPH_DATASET_NAME}" \
          --LocalExport-export-task-type ExportGraph \
          --ExportGraph-config-file "${SWH_CONFIG_FILENAME}" \
          --ExportGraph-process "${NB_PROCESSES}" \
          --CompressGraph-check-flavor "none" \
          --log-level "${LOG_LEVEL}" \
          --Llp-gammas=-1,-2,-3,-4

{{ end }}
