{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $datasetsConfig := $datasetsGeneratorConfig.datasets -}}
{{- if or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasets-script-utils
  namespace: {{ .Values.namespace }}
data:
  cleanup-generated-compressed-graph.sh: |
    #!/usr/bin/env bash
    # Uses env variables:
    # - GRAPH_DIRECTORY_PATH
    # Uses optional env variables:
    # - GRAPH_SENSITIVE_DIRECTORY_PATH
    set -e

    if [ -n "${SWH_DEBUG_ENTRYPOINT}" ]; then
        set -x
    fi

    [ -z "${GRAPH_DIRECTORY_PATH}" ] && \
      echo "<GRAPH_DIRECTORY_PATH> env variable must be set" && exit 1

    rm -rf "${GRAPH_DIRECTORY_PATH}"/{.*,*} && \
      echo "Cleanup <${GRAPH_DIRECTORY_PATH}> done"

    if [ -n "${GRAPH_SENSITIVE_DIRECTORY_PATH}" ]; then
      rm -rf "${GRAPH_SENSITIVE_DIRECTORY_PATH}"/{.*,*} && \
        echo "Cleanup <${GRAPH_SENSITIVE_DIRECTORY_PATH}> done"
    fi

  display-compressed-graph-logs.sh: |
    #!/usr/bin/env bash
    # Uses env variables:
    # - GRAPH_COMPRESSED_DIRECTORY_PATH
    set -e

    [ -z "${GRAPH_COMPRESSED_DIRECTORY_PATH}" ] && \
      echo "<GRAPH_COMPRESSED_DIRECTORY_PATH> env variable must be set" && exit 1

    for logpath in $(ls "${GRAPH_COMPRESSED_DIRECTORY_PATH}"/logs/*); do
      echo "##################### ${logpath}"
      cat "${logpath}"
      echo
    done

  generate-and-publish-compressed-graph-dataset.sh: |
    #!/usr/bin/env bash

    # This script's main goal is to generate the compressed graph dataset.
    # Optionally, it can also publish the dataset to s3 (with the graph export
    # out of the journal as orc files). This is all driven through environment
    # variables.

    # Uses mandatory env variables:
    # - SWH_CONFIG_FILENAME
    # - LUIGI_SCHEDULER_URL
    # - GRAPH_MOUNTPOINT
    # - GRAPH_DATASET_NAME
    # - NB_PROCESSES
    # - LOG_LEVEL
    # - AWS_SECRET_ACCESS_KEY (when PUBLISH is set)
    # - AWS_ACCESS_KEY_ID (when PUBLISH is set)
    # Uses optional env variables:
    # - SWH_DEBUG_ENTRYPOINT
    # - BATCH_SIZE
    # - GRAPH_SENSITIVE_MOUNTPOINT
    # - PUBLISH

    set -e

    if [ -n "${SWH_DEBUG_ENTRYPOINT}" ]; then
        set -x
    fi

    [ -z "${SWH_CONFIG_FILENAME}" ] && \
      echo "<SWH_CONFIG_FILENAME> env variable must be set" && exit 1
    [ -z "${LUIGI_SCHEDULER_URL}" ] && \
      echo "<LUIGI_SCHEDULER_URL> env variable must be set" && exit 1
    [ -z "${GRAPH_MOUNTPOINT}" ] && \
      echo "<GRAPH_MOUNTPOINT> env variable must be set" && exit 1
    [ -z "${GRAPH_DATASET_NAME}" ] && \
      echo "<GRAPH_DATASET_NAME> env variable must be set" && exit 1
    [ -z "${NB_PROCESSES}" ] && \
      echo "<NB_PROCESSES> env variable must be set" && exit 1
    [ -z "${LOG_LEVEL}" ] && \
      echo "<LOG_LEVEL> env variable must be set" && exit 1

    # The default luigi task to generate the compressed graph
    graph_generation_task=CompressGraph

    EXTRA_CLI_FLAGS=()
    EXTRA_SUBCMD_FLAGS=()

    if [ -n "${BATCH_SIZE}" ]; then
      EXTRA_CLI_FLAGS+=('--batch-size' "${BATCH_SIZE}")
    fi

    if [ -n "${GRAPH_SENSITIVE_MOUNTPOINT}" ]; then
      EXTRA_CLI_FLAGS+=('--base-sensitive-directory' "${GRAPH_SENSITIVE_MOUNTPOINT}")
    fi

    if [ -n "${PUBLISH}" ]; then
      # When publication is enabled

      # Ensure required variables are properly set, if not raise
      [ -z "${AWS_SECRET_ACCESS_KEY}" ] && \
        echo "<AWS_SECRET_ACCESS_KEY> env variable must be set" && exit 1
      [ -z "${AWS_ACCESS_KEY_ID}" ] && \
        echo "<AWS_ACCESS_KEY_ID> env variable must be set" && exit 1

      # Add extra cli flags for the s3 publication
      EXTRA_CLI_FLAGS+=('--s3-prefix' "s3://softwareheritage/graph/")
      EXTRA_CLI_FLAGS+=('--s3-athena-output-location' "s3://softwareheritage/tmp/athena/")
      EXTRA_CLI_FLAGS+=('--athena-prefix' "swh")

      # Add some extra sub command flags (require the export to be in orc)
      EXTRA_SUBCMD_FLAGS=('--UploadExportToS3-formats' "orc")

      # Finally, we override the default luigi task to upload the compressed
      # graph dataset to s3 (this will trigger the compressed graph generation
      # first out of the graph export)
      graph_generation_task=UploadGraphToS3
    fi

    set -x

    # Trigger the compressed graph dataset (and publish to s3 if publication enabled)
    /opt/swh/entrypoint.sh \
       swh datasets luigi \
          --dataset-name "${GRAPH_DATASET_NAME}" \
          --base-directory "${GRAPH_MOUNTPOINT}" \
          "${EXTRA_CLI_FLAGS[@]}" \
          ${graph_generation_task} \
          -- \
          --scheduler-url "${LUIGI_SCHEDULER_URL}" \
          --ExportGraph-export-name "${GRAPH_DATASET_NAME}" \
          --LocalExport-export-task-type ExportGraph \
          --ExportGraph-config-file "${SWH_CONFIG_FILENAME}" \
          --ExportGraph-process "${NB_PROCESSES}" \
          --CompressGraph-check-flavor "none" \
          "${EXTRA_SUBCMD_FLAGS[@]}" \
          --log-level "${LOG_LEVEL}"

    if [ -n "${PUBLISH}" ]; then
      # When publication is enabled, this publishes the graph export (as orc
      # files) to s3
      /opt/swh/entrypoint.sh \
         swh datasets luigi \
            --dataset-name "${GRAPH_DATASET_NAME}" \
            --base-directory "${GRAPH_MOUNTPOINT}" \
            "${EXTRA_CLI_FLAGS[@]}" \
            UploadExportToS3 \
            -- \
            --scheduler-url "${LUIGI_SCHEDULER_URL}" \
            --ExportGraph-export-name "${GRAPH_DATASET_NAME}" \
            --LocalExport-export-task-type ExportGraph \
            --ExportGraph-config-file "${SWH_CONFIG_FILENAME}" \
            --ExportGraph-process "${NB_PROCESSES}" \
            --CompressGraph-check-flavor "none" \
            "${EXTRA_SUBCMD_FLAGS[@]}" \
            --log-level "${LOG_LEVEL}"
    fi

{{ end }}
