{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $luigiSchedulerConfig := $datasetsGeneratorConfig.scheduler -}}

{{- if (and (ne false $datasetsGeneratorConfig.enabled)
            (ne false $luigiSchedulerConfig.enabled)) -}}
{{- $schedulerConfig := include "swh.luigi.scheduler.config"
                                (dict "luigiSchedulerConfig"    $luigiSchedulerConfig
                                      "datasetsGeneratorConfig" $datasetsGeneratorConfig
                                      "Values"                  $.Values) | fromYaml -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: luigi-config-utils
  namespace: {{ $schedulerConfig.namespace }}
data:
  prepare-configuration.sh: |
    #!/bin/bash

    set -eu

    export POD_IP=$(hostname -i)

    echo "Following variables will be replaced:"
    envsubst -v "$(<${CONFIG_TEMPLATE_PATH})"

    cat "${CONFIG_TEMPLATE_PATH}" | envsubst > "${CONFIG_PATH}"
{{- end -}}
