{{- $datasetExporterConfig := .Values.datasetsGenerator -}}
{{- $deploymentConfig := $datasetExporterConfig.scheduler -}}

{{ if and $datasetExporterConfig.enabled $deploymentConfig.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: luigi-config-utils
  namespace: {{ $.Values.namespace }}
data:
  prepare-configuration.sh: |
    #!/bin/bash

    set -eu

    export POD_IP=$(hostname -i)

    echo "Following variables will be replaced:"
    envsubst -v "$(<${CONFIG_TEMPLATE_PATH})"

    cat "${CONFIG_TEMPLATE_PATH}" | envsubst > "${CONFIG_PATH}"
{{- end -}}
