{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $luigiSchedulerConfig := $datasetsGeneratorConfig.scheduler -}}

{{- if (and (or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled"))
            (or (not (hasKey $luigiSchedulerConfig "enabled")) (get $luigiSchedulerConfig "enabled"))) -}}
{{- $schedulerConfig := include "swh.luigi.scheduler.config"
                                (dict "luigiSchedulerConfig"    $luigiSchedulerConfig
                                      "datasetsGeneratorConfig" $datasetsGeneratorConfig
                                      "Values"                  $.Values) | fromYaml -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: luigi-scheduler-script-utils
  namespace: {{ $schedulerConfig.namespace }}
data:
  luigi-scheduler-run.sh: |
    #!/usr/bin/env bash
    # Can use env variables:
    # - LUIGI_RECORD_TASK_HISTORY
    # - LUIGI_RECORD_DB_PATH
    set -e

    if [ -n "${SWH_DEBUG_ENTRYPOINT}" ]; then
        set -x
    fi

    # Prepare where to write the record task history
    if [ "${LUIGI_RECORD_TASK_HISTORY}" = "true" ]; then
        [ -z "${LUIGI_RECORD_DB_PATH}" ] && \
          echo "<LUIGI_RECORD_DB_PATH> env variable must be set" && exit 1

        mkdir -p $(dirname "${LUIGI_RECORD_DB_PATH}")
        [ ! -f "${LUIGI_RECORD_DB_PATH}" ] && touch "${LUIGI_RECORD_DB_PATH}"
    fi

    /opt/swh/entrypoint.sh

{{ end }}
