{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $luigiSchedulerConfig := $datasetsGeneratorConfig.scheduler -}}
{{- $containerImageKey := $datasetsGeneratorConfig.image -}}
{{- $containerImage := .Values.swh_datasets_image -}}
{{- $containerImageVersion := .Values.swh_datasets_image_version -}}

{{- if (and (or (not (hasKey $datasetsGeneratorConfig "enabled")) (get $datasetsGeneratorConfig "enabled"))
            (or (not (hasKey $luigiSchedulerConfig "enabled")) (get $luigiSchedulerConfig "enabled"))) -}}
{{- $configChecksum := include (print $.Template.BasePath "/datasets-generator/scheduler-luigi-configmap.yaml") . | sha256sum -}}
{{- $configUtilsChecksum := include (print $.Template.BasePath "/datasets-generator/luigi-config-utils.yaml") . | sha256sum -}}

{{- $schedulerConfig := include "swh.luigi.scheduler.config"
                                (dict "luigiSchedulerConfig"    $luigiSchedulerConfig
                                      "datasetsGeneratorConfig" $datasetsGeneratorConfig
                                      "Values"                  $.Values) | fromYaml -}}
{{- $serviceType := $schedulerConfig.serviceType -}}
{{- $namespace := $schedulerConfig.namespace -}}
{{- $replicas := $schedulerConfig.replicas -}}
{{- $affinity := $schedulerConfig.affinity -}}
{{- $priorityClassName := $schedulerConfig.priorityClassName -}}
{{- $port := $schedulerConfig.port -}}
{{- $type := $schedulerConfig.type -}}
{{- $path := $schedulerConfig.path -}}
{{- $debug := $schedulerConfig.debug -}}
{{- $luigiConfigDirpath := $schedulerConfig.luigiConfigDirpath -}}
{{- $luigiConfigPath := $schedulerConfig.luigiConfigPath -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $namespace }}
  name: {{ $serviceType }}
  labels:
    app: {{ $serviceType }}
spec:
  revisionHistoryLimit: 2
  {{ if $replicas -}}
  replicas: {{ $replicas }}
  {{ end -}}
  selector:
    matchLabels:
      app: {{ $serviceType }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $serviceType }}
      annotations:
        checksum/config: {{ $configChecksum }}
        checksum/config-utils: {{ $configUtilsChecksum }}
    spec:
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if and .Values.podPriority.enabled $priorityClassName }}
      priorityClassName: {{ print $namespace "-" $priorityClassName | quote }}
      {{ end }}
      initContainers:
        - name: prepare-configuration
          image: {{ $.Values.swh_utils_image }}:{{ $.Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          command:
          - /entrypoints/prepare-configuration.sh
          env: {{ include "swh.secrets.envFromDeploymentConfig" (dict "deploymentConfig" $luigiSchedulerConfig
                                                                      "Values" $.Values) | nindent 10 }}
            - name: CONFIG_TEMPLATE_PATH
              value: {{ print $luigiConfigDirpath "/configuration-template/luigi.cfg.template" }}
            - name: CONFIG_PATH
              value: {{ $luigiConfigPath }}
          volumeMounts:
          - name: configuration
            mountPath: {{ $luigiConfigDirpath }}
          - name: configuration-template
            mountPath: {{ print $luigiConfigDirpath "/configuration-template" }}
          - name: luigi-config-utils
            mountPath: /entrypoints
            readOnly: true
      containers:
        - name: {{ $serviceType }}
          resources:
            requests:
              memory: {{ $luigiSchedulerConfig.requestedMemory | default "512Mi" }}
              cpu: {{ $luigiSchedulerConfig.requestedCpu | default "500m" }}
          {{- if or $luigiSchedulerConfig.limitedMemory $luigiSchedulerConfig.limitedCpu }}
            limits:
            {{- if $luigiSchedulerConfig.limitedMemory }}
              memory: {{ $luigiSchedulerConfig.limitedMemory }}
            {{- end }}
            {{- if $luigiSchedulerConfig.limitedCpu }}
              cpu: {{ $luigiSchedulerConfig.limitedCpu }}
            {{- end }}
        {{- end }}
          image: {{ print $containerImage ":" $containerImageVersion | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $port }}
              name: {{ $type }}
          {{- if $debug }}
          command:
          - /bin/sleep
          args:
          - "3600"
          {{- else }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ $type }}
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ $type }}
            initialDelaySeconds: 10
            periodSeconds: 5
          command:
          - /script/luigi-scheduler-run.sh
          {{- end }}
          env:
            - name: LUIGI_PATH_TO_PIDFILE
              value: {{ $path }}/pid
            - name: LUIGI_PATH_TO_LOGDIR
              value: {{ $path }}/log
            - name: LUIGI_PATH_TO_STATEFILE
              value: {{ $path }}/state
            - name: LUIGI_CONFIG_PATH
              value: {{ $luigiConfigPath }}
            - name: LUIGI_CONFIG_PARSER
              value: cfg
            - name: LUIGI_RECORD_TASK_HISTORY
              value: {{ $schedulerConfig.recordTaskHistory | quote }}
            - name: LUIGI_RECORD_DB_PATH
              value: {{ $schedulerConfig.recordDbPath }}
          volumeMounts:
          - name: configuration
            mountPath: {{ $luigiConfigDirpath }}
          - name: luigi-scheduler-script-utils
            mountPath: /script
      volumes:
      - name: configuration
        emptyDir: {}
      - name: configuration-template
        configMap:
          name: scheduler-luigi-configmap-configuration-template
          items:
          - key: "luigi.cfg.template"
            path: "luigi.cfg.template"
      - name: luigi-config-utils
        configMap:
          name: luigi-config-utils
          defaultMode: 0555
      - name: luigi-scheduler-script-utils
        configMap:
          name: luigi-scheduler-script-utils
          defaultMode: 0555
{{- end -}}
