{{- $datasetsGeneratorConfig := .Values.datasetsGenerator -}}
{{- $luigiSchedulerConfig := $datasetsGeneratorConfig.scheduler -}}

{{- if (and (ne false $datasetsGeneratorConfig.enabled)
            (ne false $luigiSchedulerConfig.enabled)) -}}
{{- $schedulerConfig := include "swh.luigi.scheduler.config"
                                (dict "luigiSchedulerConfig"    $luigiSchedulerConfig
                                      "datasetsGeneratorConfig" $datasetsGeneratorConfig
                                      "Values"                  $.Values) | fromYaml -}}
{{- $recordTaskHistory := $schedulerConfig.recordTaskHistory -}}
{{- $orgRamMb := $schedulerConfig.orgRamMb -}}

{{- include "swh.datasets.config.luigi" (dict "schedulerConfig" $schedulerConfig
                                             "configmapName"   "scheduler-luigi-configmap-configuration-template"
                                             "namespace"       $schedulerConfig.namespace
                                             "logLevel"        $schedulerConfig.logLevel) }}

    {{- if $recordTaskHistory }}
    [scheduler]
    record_task_history = {{ $recordTaskHistory }}

    [task_history]
    db_connection = sqlite:///{{ $schedulerConfig.recordDbPath }}
    {{- end }}

    [resources]
    {{ if $orgRamMb }}
    {{- range $datasetGeneratorName, $datasetGeneratorConfig := $datasetsGeneratorConfig.datasets.deployments -}}
    {{- if and (ne false $datasetsGeneratorConfig.enabled)
               (ne false $datasetGeneratorConfig.enabled) -}}
      {{- $config := include "swh.datasets.generator.config"
      (dict "datasetGeneratorName"           $datasetGeneratorName
            "datasetGeneratorConfiguration"  $datasetGeneratorConfig
            "datasetsGeneratorConfiguration" $datasetsGeneratorConfig
            "Values"                         $.Values) | fromYaml -}}
    {{ $config.serviceType }}_ram_mb = {{ $orgRamMb }}
    {{ end }}
    {{- end }}
    {{- end }}

{{- end -}}
