{{- if .Values.staticWebsites.enabled }}
{{ range $websiteName, $websiteConfig := .Values.staticWebsites.deployments }}
{{- if $websiteConfig.enabled  -}}
{{ $appName := print "website-" $websiteName }}
{{ $namespace := $websiteConfig.namespace | default $.Values.staticWebsites.namespace | default $.Values.namespace }}
{{ $replicas := $websiteConfig.replicas | default $.Values.staticWebsites.replicas }}
{{ $image := $websiteConfig.image -}}
{{ $imageVersion := $websiteConfig.imageVersion | default "latest" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      {{- if $.Values.staticWebsites.affinity }}
      affinity:
        {{- toYaml $.Values.staticWebsites.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $appName }}
          image: {{ $image }}:{{ $imageVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80

{{- end }}
{{- end }}
{{- end }}
