{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.vaultStaticSecrets.enabled (ne $clusterName "local-cluster") -}}
  {{- $defaultSyncPeriod := .Values.vaultStaticSecrets.refreshAfter -}}
  {{- $namespace := .Values.namespace -}}
  {{- $vaultAuthRef := .Values.vaultAuthRef -}}
  {{- $secrets := list -}}
  {{- range $secretName, $secretConfig := .Values.vaultStaticSecrets.secrets }}
    {{- if $secretConfig.enabled }}
      {{- $namespaces := $secretConfig.namespaces | default (list $namespace) -}}
      {{- range $namespace := $namespaces }}
        {{- $type := $secretConfig.type | default "Opaque" -}}
        {{- $syncPeriod := $secretConfig.syncPeriod | default $defaultSyncPeriod -}}
        {{- $secrets = append $secrets (list $namespace $type $secretName $syncPeriod)  -}}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- range $secret := $secrets | uniq }}
  {{ $secretNamespace := index $secret 0 }}
  {{ $secretType := index $secret 1 }}
  {{ $secretName := index $secret 2 }}
  {{ $secretSyncPeriod := index $secret 3 }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $secretNamespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
    {{- if eq $secretType "cnpg" }}
    labels:
      cnpg.io/reload: "true"
    type: kubernetes.io/basic-auth
    {{- end }}
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: {{ $secretSyncPeriod }}
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{- end }}

