{{ if .Values.vaultSecretsOperator.enabled }}
{{- $namespace := .Values.vaultSecretsOperator.namespace -}}
{{- $appName := print .Values.clusterName "-vault-secrets-operator" -}}
{{- $version := .Values.vaultSecretsOperator.version -}}
{{- $prune := .Values.vaultSecretsOperator.argocdApplication.prune | default .Values.defaultPrune -}}
{{- $selfHeal := .Values.vaultSecretsOperator.argocdApplication.selfHeal | default .Values.defaultSelfHeal -}}
{{- $logLevel := .Values.vaultSecretsOperator.logLevel | default "info" -}}
{{- $openbaoEndpoint := .Values.vaultSecretsOperator.openbaoEndpoint -}}
{{- $hostAliases := .Values.vaultSecretsOperator.hostAliases | default list -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com/
    chart: vault-secrets-operator
    targetRevision: v{{ $version }}
    helm:
      releaseName: vso
      values: |
        controller:
          manager:
            logging:
              level: {{ $logLevel }}
          {{- if $hostAliases }}
          hostAliases:
            {{- toYaml $hostAliases | nindent 12 }}
          {{- end }}
        defaultVaultConnection:
          enabled: true
          address: {{ $openbaoEndpoint }}
  destination:
    server: {{ .Values.clusterUrl }}
    namespace: {{ $namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: {{ $prune }}
      selfHeal: {{ $selfHeal }}
{{ end }}
