{{- if .Values.postgresqlTest.enabled }}

{{- $namespace := .Values.postgresqlTest.namespace }}

apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  namespace: {{ $namespace }}
  labels:
    app: postgres-test

spec:
  type: ClusterIP

  selector:
    app: postgres-test

  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres

{{- end }}