{{- if .Values.keycloak.enabled }}
{{- $appName := printf "%s-keycloak" .Values.clusterName }}
{{- $namespace := .Values.keycloak.namespace }}
{{- $image := .Values.keycloak.image }}
{{- $imageVersion := .Values.keycloak.imageVersion | default "latest" }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $appName }}

spec:
  serviceName: {{ printf "%s-discovery" $appName }}
  replicas: {{ .Values.keycloak.replicas | default 2 }}

  selector:
    matchLabels:
      app: {{ $appName }}

  template:
    metadata:
      labels:
        app: {{ $appName }}

    spec:
      restartPolicy: Always

      containers:
        - name: {{ $appName }}
          image: "{{ $image }}:{{ $imageVersion }}"
          imagePullPolicy: IfNotPresent

          args:
            - start

          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminSecret.name }}
                  key: username

            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminSecret.name }}
                  key: password

            - name: KC_PROXY_HEADERS
              value: "xforwarded"

            - name: KC_HTTP_ENABLED
              value: "true"

            - name: KC_HOSTNAME_STRICT
              value: "false"

            - name: KC_HEALTH_ENABLED
              value: "true"

            - name: KC_CACHE
              value: "ispn"

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: KC_DB
              value: "postgres"

            - name: KC_DB_URL_HOST
              value: {{ .Values.keycloak.database.host | quote }}

            - name: KC_DB_URL_DATABASE
              value: {{ .Values.keycloak.database.name | quote }}

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.postgresSecret.name | quote }}
                  key: username

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.postgresSecret.name | quote }}
                  key: password

          ports:
            - name: http
              containerPort: 8080

            - name: management
              containerPort: 9000

            - name: jgroups
              containerPort: 7800

            - name: jgroups-fd
              containerPort: 57800

          startupProbe:
            httpGet:
              path: /health/started
              port: management
            periodSeconds: 1
            failureThreshold: 600

          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/live
              port: management
            periodSeconds: 10
            failureThreshold: 3

          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1700Mi

{{- end }}