{{ if .Values.storage.enabled -}}
{{ range $storage_type, $storage_config := .Values.storage.deployments }}
{{- if (ne false $storage_config.enabled) -}}
{{ range $cron_job, $cron_config := $storage_config.cronjobs | default dict }}
{{- if (ne false $cron_config.enabled) -}}
{{ include "swh.storage.configmap" (dict "serviceType" (print "cronjob-" $cron_job)
                                         "configuration" $cron_config
                                         "Values" $.Values) }}
{{- end -}}
{{- end -}}
{{- end -}}
{{ end -}}
{{- end -}}
