{{ if .Values.rabbitmq.enabled -}}
  {{- $appName := print .Values.clusterName "-rabbitmq-operator" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  revisionHistoryLimit: 2
  project: {{ .Values.defaultProject }}
  sources:
    - repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git/'
      targetRevision: {{ .Values.environment }}
      path: ./cluster-configuration/template/rabbitmq-operator
      directory:
        include: cluster-operator-{{ .Values.rabbitmq.version }}.yml
    - repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git/'
      targetRevision: {{ .Values.environment }}
      path: ./cluster-configuration/template/rabbitmq-operator
      directory:
        include: messaging-topology-operator-with-certmanager-{{ .Values.rabbitmq.messagingTopologyOperatorVersion }}.yml
  destination:
    server: {{ .Values.clusterUrl }}
    namespace: {{ .Values.rabbitmq.namespace | default "rabbitmq" | quote }}
  syncPolicy:
    automated:
      prune: {{ .Values.defaultPrune }}
      selfHeal: {{ .Values.defaultSelfHeal }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - kind: Secret
      name: {{ printf "%s%s" $appName "-rabbitmq-messaging-topology" | trunc 63 }}
      namespace: {{ .Values.rabbitmq.namespace }}
      jsonPointers:
        - /data
{{ end }}
