{{ if .Values.vulns.enabled -}}
{{- $backendUtilsChecksum := include (print $.Template.BasePath "/utils/backend-utils.yaml") . | sha256sum -}}
{{ range $vulnsInstanceName, $vulnsConfig := .Values.vulns.deployments }}
{{- if and (ne false $vulnsConfig.enabled)
           (or (not (hasKey $vulnsConfig "startService")) (get $vulnsConfig "startService")) -}}
{{- $serviceType := ( print "vulns-" $vulnsInstanceName ) -}}
{{- $configArgsDict := dict "serviceType" $serviceType
                            "configuration" $vulnsConfig
                            "Values" $.Values -}}
{{- $securityContext := $vulnsConfig.securityContext | default $.Values.vulns.securityContext -}}
{{- $port := $vulnsConfig.port -}}
{{- $datasetName := dig "dataset" "name" "" $vulnsConfig | default $vulnsInstanceName -}}
{{- $fetchVulnsDataset := dig "dataset" "fetch" false $vulnsConfig -}}
{{- $vulnsDatasetPath := print "/srv/dataset/" $datasetName -}}
{{- $vulnDbPath := print $vulnsDatasetPath "/all.sqlite" -}}
{{- $vulnCommit2VulnPath := print $vulnsDatasetPath "/commit2vuln_without_cherrypicks" -}}
{{- $vulnSubgraphWccsPath := print $vulnsDatasetPath "/connected_components.wccs" -}}
{{- $graphName := dig "dataset" "graphName" "" $vulnsConfig | default $vulnsInstanceName -}}
{{- $graphDatasetPath := print "/srv/graph/" $graphName "/compressed/graph" -}}
{{- $vulnsImage := get $vulnsConfig "image" | default $.Values.vulns.image | default $.Values.swh_vulns_image -}}
{{- $vulnsImageVersion := get $vulnsConfig "imageVersion" | default $.Values.vulns.imageVersion | default $.Values.swh_vulns_image_version -}}
{{- $logLevel := $vulnsConfig.logLevel | default $.Values.vulns.logLevel | default "INFO" | upper -}}
{{- $toolbox := and $vulnsConfig.toolbox $vulnsConfig.toolbox.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $serviceType }}
  labels:
    app: {{ $serviceType }}
spec:
  revisionHistoryLimit: 2
  {{ if $vulnsConfig.replicas -}}
  replicas: {{ $vulnsConfig.replicas | default $.Values.vulns.replicas }}
  {{ end -}}
  selector:
    matchLabels:
      app: {{ $serviceType }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $serviceType }}
      annotations:
        checksum/backend-utils: {{ $backendUtilsChecksum }}
    spec:
      {{- if $securityContext }}
      securityContext:
        {{- toYaml $securityContext | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := $vulnsConfig.nodeSelector | default $.Values.vulns.nodeSelector | default dict -}}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- $affinity := $vulnsConfig.affinity | default $.Values.vulns.affinity | default dict -}}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}

      {{- if and $.Values.podPriority.enabled $.Values.vulns.priorityClassName }}
      priorityClassName: {{ $.Values.namespace }}-{{ $.Values.vulns.priorityClassName }}
      {{- end }}
      initContainers:
        {{- if $fetchVulnsDataset }}
        {{- $datasetUrl := required "Dataset url must be provided" (dig "dataset" "url" "" $vulnsConfig) -}}
        {{ include "swh.vulns.fetchDataset" (dict "Values" $.Values
                                                  "imagePrefixName" "swh_vulns_image"
                                                  "imageVersion" $vulnsImageVersion
                                                  "datasetUrl" $datasetUrl
                                                  "datasetPath" $vulnsDatasetPath
                                                  "extraVolumes" $vulnsConfig.extraVolumes) | nindent 8 }}
        {{ include "swh.vulns.waitForDataset" (dict "Values" $.Values
                                                    "datasetPath" $vulnsDatasetPath
                                                    "extraVolumes" $vulnsConfig.extraVolumes) | nindent 8 }}
        {{ end }}
      containers:
        - name: {{ $serviceType }}
          resources:
            requests:
              memory: {{ $vulnsConfig.requestedMemory | default "512Mi" }}
              cpu: {{ $vulnsConfig.requestedCpu | default "500m" }}
            {{- if or $vulnsConfig.limitedMemory $vulnsConfig.limitedCpu }}
              limits:
              {{- if $vulnsConfig.limitedMemory }}
              memory: {{ $vulnsConfig.limitedMemory }}
              {{- end }}
              {{- if $vulnsConfig.limitedCpu }}
              cpu: {{ $vulnsConfig.limitedCpu }}
              {{- end }}
            {{- end }}
          image: {{ $vulnsImage }}:{{ $vulnsImageVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $port }}
              name: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            periodSeconds: 5
          command:
          {{- if $toolbox }}
          - /bin/sleep
          args:
          - infinity
          {{- else }}
          - /bin/bash
          args:
          - -c
          - /opt/swh/entrypoint.sh
          {{ end }}
          env:
            - name: PORT
              value: {{ $port | quote }}
            - name: GRAPH_DATASET_PATH
              value: {{ $graphDatasetPath }}
            - name: VULN_DB_PATH
              value: {{ $vulnDbPath }}
            - name: VULN_COMMIT2VULN_PATH
              value: {{ $vulnCommit2VulnPath }}
            - name: VULN_SUBGRAPHWCCS_PATH
              value: {{ $vulnSubgraphWccsPath }}
            - name: STATSD_HOST
              value: {{ $.Values.statsdExternalHost | default "prometheus-statsd-exporter" }}
            - name: STATSD_PORT
              value: {{ $.Values.statsdPort | default "9125" | quote }}
            - name: STATSD_TAGS
              value: deployment:{{ $serviceType }}
            - name: STATSD_SERVICE_TYPE
              value: {{ $serviceType }}
            - name: DO_NOT_CHECK_MOD_TIMES
              value: "true"
            {{- if (eq (lower $logLevel) "debug") }}
            - name: RUST_LOG
              value: "debug"
            {{ end }}
          {{- if $.Values.vulns.sentry.enabled }}
            - name: SWH_SENTRY_ENVIRONMENT
              value: {{ $.Values.sentry.environment }}
            - name: SWH_MAIN_PACKAGE
              value: swh.vulns
            - name: SWH_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.vulns.sentry.secretKeyRef }}
                  key: {{ $.Values.vulns.sentry.secretKeyName }}
                  # 'name' secret should exist & include key
                  # if the setting doesn't exist, sentry pushes will be disabled
                  optional: true
            - name: SWH_SENTRY_DISABLE_LOGGING_EVENTS
              value: "true"
          {{- end }}
          volumeMounts:
          {{- range $volumeName, $volumeConfig := $vulnsConfig.extraVolumes }}
          - name: {{ $volumeName }}
            mountPath: {{ $volumeConfig.mountPath }}
            readOnly: {{ $volumeConfig.readOnly | default "false" }}
          {{ end }}
      volumes:
      - name: config-utils
        configMap:
          name: config-utils
          defaultMode: 0555
      - name: backend-utils
        configMap:
          name: backend-utils
          defaultMode: 0555
      {{- range $volumeName, $volumeConfig := $vulnsConfig.extraVolumes }}
      {{- $pvcName := $volumeConfig.pvcName }}
      - name: {{ $volumeName }}
        {{- toYaml $volumeConfig.volumeDefinition | nindent 8 }}
      {{ end }}
{{ end }}
{{ end -}}
{{- end -}}
