{{- if .Values.openbao.enabled }}
{{- $namespace := .Values.openbao.namespace -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-script-utils
  namespace: {{ $namespace }}
data:
  init_bao_cluster.py: |
    #!/usr/bin/env python3

    # Script in charge to manage the bao cluster initialization
    # - enable kv-v2 secret
    # - enable approle authentication
    # - write policy access (for an approle)
    # - create said approle

    # See documentation and examples here:
    # https://developer.hashicorp.com/vault/api-docs/system/mounts
    # https://support.hashicorp.com/hc/en-us/articles/4412233931667-Translate-Vault-CLI-commands-to-HTTP-API
    # https://gist.github.com/exAspArk/e210523a4bcb988cdfb24a114d46ddf0

    import click
    import hvac
    from typing import Optional


    def get_client(
        url: str, token: Optional[str] = None, no_verify_ssl: bool = False
    ) -> hvac.Client:
        """Client HVAC Initialization"""
        # TODO: Turn off the verify to True (for tls authentication)
        client = hvac.Client(url=url, token=token, verify=not no_verify_ssl)
        if not client.is_authenticated():
            raise ValueError("Impossible to authenticate with Vault/OpenBao.")
        return client


    @click.group()
    @click.option('--url', required=True, help="Vault/OpenBao URL")
    @click.option('--token', required=True, help="Vault/OpenBao Access Token")
    @click.option('--no-verify-ssl', is_flag=True, default=False, help="Allow to disable ssl check")
    @click.pass_context
    def cli(ctx, url, token, no_verify_ssl):
        """Mount initialization"""

        ctx.ensure_object(dict)
        ctx.obj['client'] = get_client(url, token, no_verify_ssl)


    @cli.command()
    @click.argument('path')
    @click.argument('backend_type', default='kv')
    @click.pass_context
    def enable_secrets_engine(ctx, path, backend_type):
        """Vault/OpenBao initialization"""
        client = ctx.obj['client']

        # FIXME: Improve creation without try/except pattern
        try:
            client.sys.enable_secrets_engine(
                backend_type=backend_type,
                path=path,
                options={'version': '2'}
            )
            msg = f"Mount '{path}' with type '{backend_type}' created."
            click.echo()
        except:
            msg = f"Mount '{path}' with type '{backend_type}' already exists."
        finally:
            click.echo(msg)


    def read_app_role(client, role_name, mount):
        """Retrieve app role"""
        return client.auth.approle.read_role_id(role_name, mount_point=mount)


    @cli.command()
    @click.argument('policy_name')
    @click.argument('policy_rule_filename', type=click.Path(exists=True))
    @click.pass_context
    def create_policy(ctx, policy_name, policy_rule_filename):
        """Create policy in Vault/OpenBao."""
        client = ctx.obj['client']
        with open(policy_rule_filename, 'r') as f:
            rules = ''.join(f.readlines())

        client.sys.create_or_update_policy(
            name=policy_name,
            policy=rules
        )
        msg = f"Policy '{policy_name}' upserted."
        click.echo(msg)


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.option('--policy-name', required=True, help="Policy for that appRole")
    @click.pass_context
    def create_approle(ctx, role_name, mount, policy_name):
        """Create AppRole in Vault/OpenBao."""
        client = ctx.obj['client']
        # Enable approle authentication
        try:
            client.sys.enable_auth_method(
                method_type='approle',
                path=mount
            )
        except:
            # Already enabled, so we skip that step
            pass

        app_role = client.auth.approle
        try:
            app_role.read_role(role_name, mount_point=mount)
            msg = f"AppRole '{role_name}' already exists with role-id"
        except:
            app_role.create_or_update_approle(
                role_name=role_name,
                mount_point=mount,
                token_policies=[policy_name],
                 # Time before the AppRole Secret ID expires.
                secret_id_ttl='24h'
                # Lifetime of the token issued after AppRole authentication.
                token_ttl='1hm'
                # Maximum lifetime a token can have, even after renewals.
                token_max_ttl='4hm'
            )
            msg = f"AppRole '{role_name}' created with role-id"

        role_id = get_role_id(client, role_name, mount)
        click.echo(f"{msg} {role_id}")


    def get_role_id(client, role_name, mount):
        """Retrieve the role id from the role name mounted in the path mount."""
        app_role_d = client.auth.approle.read_role_id(role_name, mount_point=mount)
        return app_role_d['data']['role_id']


    def generate_secret_id(client, role_name, mount):
        """Generate a secret id from the role name mounted in the path mount."""
        secret_id_d = client.auth.approle.generate_secret_id(role_name, mount_point=mount)
        return secret_id_d['data']['secret_id']


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.pass_context
    def get_approle_id(ctx, role_name, mount):
        """Retrieve the role id from the role_name."""
        client = ctx.obj['client']
        role_id = get_role_id(client, role_name, mount)
        click.echo(role_id)


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.pass_context
    def create_approle_secret_id(ctx, role_name, mount):
        """Create an approle's secret id from the role_name."""
        client = ctx.obj['client']
        secret_id = generate_secret_id(client, role_name, mount)
        click.echo(secret_id)


    def build_secret(client, secret_name: str, secret_data: str):
        """Create a basic kubernetes secret object ready to be sent to the api.

        Return
            The dict created for the secret with the form {id: b64encode(secret_data)}.

        """
        from base64 import b64encode

        secret = client.V1Secret()
        secret.metadata = client.V1ObjectMeta(name=secret_name)
        secret.type = "Opaque"
        secret.data = {"id": b64encode(secret_data.encode()).decode()}

        return secret


    def create_secret_in_kube(client, api_client, secret_name, namespaces, secret):
        """Actually call the creation  of the secret object ready to be sent to the api.

        """
        api_instance = client.CoreV1Api(api_client=api_client)
        try:
            # We try to create the actual secret
            api_instance.create_namespaced_secret(namespace=namespaces, body=secret)
        except:
            # it can raise a conflict if it already exist, so we try to delete it first
            api_instance.delete_namespaced_secret(secret_name, namespaces)
            # Then we try to create it again
            api_instance.create_namespaced_secret(namespace=namespaces, body=secret)


    @cli.command()
    @click.option('--role-name', required=True, help="AppRole name")
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.option('--targeted-cluster-url', required=True,
                  help="Ingress targeted cluster url")
    @click.option('--role-id-secret-name', required=True,
                  help="Name of the secret for the role id in the target cluster")
    @click.option('--secret-name', required=True,
                  help="Name of the secret in the target cluster")
    @click.option('--namespaces', "all_namespaces", required=True,
                  help="Namespaces where to write the secret and vault auth objects in the targeted cluster")
    @click.option('--kubeconfig', "kubeconfig_path", default=None, type=click.Path(exists=True))
    @click.option('--debug', is_flag=True, default=False, help="Allow to enable more information")
    @click.pass_context
    def create_vault_auth_in_targeted_cluster(
        ctx, role_name, mount, targeted_cluster_url, role_id_secret_name, secret_name,
        all_namespaces, kubeconfig_path, debug
    ):
        """Create the VaultAuth object in targeted cluster with approle id/secret-id.

        This requires to first create the secret-id associated to the AppRole. And then
        create a VaultAuth object that references the AppRole and AppRole's Secret id.

        This then will allow the various VaultStaticSecret mappings to synchronize the
        secrets from openbao to the kubernetes cluster.

        """
        from os import environ

        hvac_client = ctx.obj['client']
        role_id = get_role_id(hvac_client, role_name, mount)

        click.echo(f"AppRole {role_id} for kubernetes client cluster authentication")

        secret_id = generate_secret_id(hvac_client, role_name, mount)

        from kubernetes import client, config
        from kubernetes.client.configuration import Configuration

        # Initialize connection to targeted kubernetes cluster
        client_config = Configuration()
        client_config.host = targeted_cluster_url
        # Typically for local clusters, we cannot easily check this so it's disabled
        client_config.verify_ssl = not environ.get('NO_VERIFY_SSL')
        # Bearer token api authentication
        client_config.api_key_prefix['authorization'] = 'Bearer'

        # If kubeconfig is passed around we use it
        if kubeconfig_path:
            from json import loads
            # Configuration file holding the bearer token
            with open(kubeconfig_path, "r") as f:
                data = loads(f.read())
            client_config.api_key['authorization'] = data['bearerToken']
        else:
            token_path = '/var/run/secrets/kubernetes.io/serviceaccount/token'
            with open(token_path, "r") as f:
                client_config.api_key['authorization'] = f.read()

        api_client = client.ApiClient(configuration=client_config)

        from kubernetes import dynamic

        # Discover the VaultAuth resource definition.
        # The group, version, and plural must match the CRD.
        group = "secrets.hashicorp.com"
        version = "v1beta1"
        api_version = f"{group}/{version}"
        kindVaultAuth = "VaultAuth"
        vault_auth_name = "openbao-vso-auth"

        # For CRDs, use the dynamic client
        dyn_client = dynamic.DynamicClient(api_client)
        vault_auth_api = dyn_client.resources.get(
            api_version=api_version,
            kind=kindVaultAuth,
        )

        from yaml import safe_dump
        from kubernetes.dynamic.exceptions import ConflictError

        namespaces = all_namespaces.split(",")
        for namespace in namespaces:
            # Create the approle id secret (key/value: "id"/role-id)
            role_id_secret = build_secret(client, role_id_secret_name, role_id)
            create_secret_in_kube(
                client, api_client, role_id_secret_name, namespace, role_id_secret
            )

            click.echo(f"AppRole {role_id} stored in kubernetes client cluster as secret")

            # Create the approle's secret (key/value: "id"/secret-id)
            secret_id_secret = build_secret(client, secret_name, secret_id)
            create_secret_in_kube(
                client, api_client, secret_name, namespace, secret_id_secret
            )

            click.echo(
                f"Associated AppRole {role_id}'s secret-id stored in kubernetes client "
                "cluster as secret"
            )

            vault_auth_manifest = {
                "apiVersion": api_version,
                "kind": kindVaultAuth,
                "metadata": {
                    "name": vault_auth_name,
                    "namespace": namespace,
                },
                "spec": {
                    "method": "appRole",
                    "mount": mount,
                    "appRole": {
                        "roleId": role_id,
                        "secretRef": secret_name,
                    },
                    "allowedNamespaces": ["*"],
                    "vaultConnectionRef": "vso/default",
                }
            }

            try:
                obj = vault_auth_api.create(
                    body=vault_auth_manifest,
                    namespace=namespace,
                )
                msg = "created"
            except (Exception, ConflictError):
                obj = vault_auth_api.patch(
                   name=vault_auth_name,
                   namespace=namespace,
                   body=vault_auth_manifest,
                   content_type="application/merge-patch+json",
                )
                msg = "updated"

            click.echo(f"VaultAuth {msg}.")
            if debug:
                click.echo(safe_dump(obj.to_dict()))


    if __name__ == '__main__':
        cli()

  init-bao-cluster.sh: |
    #!/bin/bash

    if [ ! -z "${DEBUG}" ]; then
      set -x
    fi
    [ -z "${OPENBAO_ENDPOINT}" ] && \
      echo "<OPENBAO_ENDPOINT> env variable must be set" && exit 1
    [ -z "${OPENBAO_DEFAULT_TOKEN}" ] && \
      echo "<OPENBAO_DEFAULT_TOKEN> env variable must be set" && exit 1
    [ -z "${OPENBAO_NAMESPACE}" ] && \
      echo "<OPENBAO_NAMESPACE> env variable must be set" && exit 1
    [ -z "${POLICY_NAME}" ] && \
      echo "<POLICY_NAME> env variable must be set" && exit 1
    [ -z "${MOUNT}" ] && \
      echo "<MOUNT> env variable must be set" && exit 1
    [ -z "${ROLE}" ] && \
      echo "<ROLE> env variable must be set" && exit 1
    [ -z "${BAO_SCRIPT}" ] && \
      echo "<BAO_SCRIPT> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_URL}" ] && \
      echo "<CLUSTER_TARGET_URL> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_ROLE_ID_SECRET_NAME}" ] && \
      echo "<CLUSTER_TARGET_ROLE_ID_SECRET_NAME> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_SECRET_NAME}" ] && \
      echo "<CLUSTER_TARGET_SECRET_NAME> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_NAMESPACES}" ] && \
      echo "<CLUSTER_TARGET_NAMESPACES> env variable must be set" && exit 1

    TEMP_DIR=$(mktemp -d)

    # FIXME: Move this part inside the dedicated swh-apps image (currently toolbox is
    # used)
    uv pip install hvac click kubernetes

    SCRIPT_ARGS=()
    SCRIPT_ARGS+=("--url" "${OPENBAO_ENDPOINT}")
    SCRIPT_ARGS+=("--token" "${OPENBAO_DEFAULT_TOKEN}")

    if [ ! -z "${NO_VERIFY_SSL}" ]; then
      SCRIPT_ARGS+=(--no-verify-ssl)
    fi

    function do_execute {
        # Execute command with or without redirection of warning/error to /dev/null The
        # behavior depends on the DEBUG environment variable set. When unset, the
        # default, this redirects warnings/errors to /dev/null (so output is readable)
        # If there is any issues, toggle the DEBUG on to see the potential errors (set
        # the template's value "debug" to true for this)
      if [ ! -z ${DEBUG} ]; then
        "$@"
      else
        "$@" 2>/dev/null
      fi
    }

    # Enable the secret engine on the MOUNT value
    do_execute ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" enable-secrets-engine ${MOUNT}

    # Then we create the policy for the future approle to create
    POLICY_FILENAME="${POLICY_NAME}.hcl"
    POLICY_FILE="${TEMP_DIR}/${POLICY_FILENAME}"
    # FIXME: For the migration period, let's add the create/update permissions.
    # Tol remove once the migration is done.
    cat > "${POLICY_FILE}" << EOF
    path "${MOUNT}/data/*" {
      capabilities = ["list", "read", "create", "update"]
    }

    path "${MOUNT}/metadata/*" {
      capabilities = ["list", "read", "create", "update"]
    }
    EOF

    echo "Policy to create:"
    cat "${POLICY_FILE}"

    # Create the policy to allow read access (and temporarily write access, for the time
    # of the migration, see previous comment)
    do_execute ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-policy ${POLICY_NAME} ${POLICY_FILE}

    # Then, attach that policy to the new AppRole we create to allow the cluster's
    # VaultAuth to connect to the openbao instance in the admin cluster
    do_execute ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-approle \
      --mount ${MOUNT} \
      --policy-name ${POLICY_NAME} \
      ${ROLE}

    extra_args=()
    if [ ! -z ${CLUSTER_TARGET_KUBECONFIG} ]; then
      extra_args+=("--kubeconfig" "${CLUSTER_TARGET_KUBECONFIG}")
    fi
    if [ ! -z ${DEBUG} ]; then
      extra_args+=("--debug")
    fi

    # Finally, generate the appRole's secret id and reference the appRole and secret id
    # in the cluster client of the openbao instance.
    do_execute ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-vault-auth-in-targeted-cluster \
      --role-name ${ROLE} \
      --mount ${MOUNT} \
      --targeted-cluster-url ${CLUSTER_TARGET_URL} \
      --role-id-secret-name ${CLUSTER_TARGET_ROLE_ID_SECRET_NAME} \
      --secret-name ${CLUSTER_TARGET_SECRET_NAME} \
      --namespaces ${CLUSTER_TARGET_NAMESPACES} \
      "${extra_args[@]}"
{{- end }}
