{{- if .Values.openbao.enabled }}
{{- $namespace := .Values.openbao.namespace -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-script-utils
  namespace: {{ $namespace }}
data:
  init_bao_cluster.py: |
    #!/usr/bin/env python3

    # Script in charge to manage the bao cluster initialization
    # - enable kv-v2 secret
    # - enable approle authentication
    # - write policy access (for an approle)
    # - create said approle

    # See documentation and examples here:
    # https://developer.hashicorp.com/vault/api-docs/system/mounts
    # https://support.hashicorp.com/hc/en-us/articles/4412233931667-Translate-Vault-CLI-commands-to-HTTP-API
    # https://gist.github.com/exAspArk/e210523a4bcb988cdfb24a114d46ddf0

    import click
    import hvac
    from typing import Optional


    def get_client(
        url: str, token: Optional[str] = None, no_verify_ssl: bool = False
    ) -> hvac.Client:
        """Client HVAC Initialization"""
        # TODO: Turn off the verify to True (for tls authentication)
        client = hvac.Client(url=url, token=token, verify=not no_verify_ssl)
        if not client.is_authenticated():
            raise ValueError("Impossible to authenticate with Vault/OpenBao.")
        return client


    @click.group()
    @click.option('--url', required=True, help="Vault/OpenBao URL")
    @click.option('--token', required=True, help="Vault/OpenBao Access Token")
    @click.option('--no-verify-ssl', is_flag=True, default=False, help="Allow to disable ssl check")
    @click.pass_context
    def cli(ctx, url, token, no_verify_ssl):
        """Mount initialization"""

        ctx.ensure_object(dict)
        ctx.obj['client'] = get_client(url, token, no_verify_ssl)


    @cli.command()
    @click.argument('path')
    @click.argument('backend_type', default='kv')
    @click.pass_context
    def enable_secrets_engine(ctx, path, backend_type):
        """Vault/OpenBao initialization"""
        client = ctx.obj['client']

        # FIXME: Improve creation without try/except pattern
        try:
            client.sys.enable_secrets_engine(
                backend_type=backend_type,
                path=path,
                options={'version': '2'}
            )
            msg = f"Mount '{path}' with type '{backend_type}' created."
            click.echo()
        except:
            msg = f"Mount '{path}' with type '{backend_type}' already exists."
        finally:
            click.echo(msg)


    def read_app_role(client, role_name, mount):
        """Retrieve app role"""
        return client.auth.approle.read_role_id(role_name, mount_point=mount)


    @cli.command()
    @click.argument('policy_name')
    @click.argument('policy_rule_filename', type=click.Path(exists=True))
    @click.pass_context
    def create_policy(ctx, policy_name, policy_rule_filename):
        """Create policy in Vault/OpenBao."""
        client = ctx.obj['client']
        with open(policy_rule_filename, 'r') as f:
            rules = ''.join(f.readlines())

        try:
            client.sys.read_policy(policy_name)
            msg = f"Policy '{policy_name}' already exists."
        except:
            client.sys.create_or_update_policy(
                name=policy_name,
                policy=rules
            )
            msg = f"Policy '{policy_name}' created."
        click.echo(msg)


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.option('--policy-name', required=True, help="Policy for that appRole")
    @click.pass_context
    def create_approle(ctx, role_name, mount, policy_name):
        """Create AppRole in Vault/OpenBao."""
        client = ctx.obj['client']
        # Enable approle authentication
        try:
            client.sys.enable_auth_method(
                method_type='approle',
                path=mount
            )
        except:
            # Already enabled, so we skip that step
            pass

        app_role = client.auth.approle
        try:
            app_role.read_role(role_name, mount_point=mount)
            msg = f"AppRole '{role_name}' already exists with role-id"
        except:
            app_role.create_or_update_approle(
                role_name=role_name,
                mount_point=mount,
                token_policies=[policy_name],
            )
            msg = f"AppRole '{role_name}' created with role-id"

        role_id = get_role_id(client, role_name, mount)
        click.echo(f"{msg} {role_id}")


    def get_role_id(client, role_name, mount):
        """Retrieve the role id from the role name mounted in the path mount."""
        app_role_d = client.auth.approle.read_role_id(role_name, mount_point=mount)
        return app_role_d['data']['role_id']


    def generate_secret_id(client, role_name, mount):
        """Generate a secret id from the role name mounted in the path mount."""
        secret_id_d = client.auth.approle.generate_secret_id(role_name, mount_point=mount)
        return secret_id_d['data']['secret_id']


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.pass_context
    def get_approle_id(ctx, role_name, mount):
        """Retrieve the role id from the role_name."""
        client = ctx.obj['client']
        role_id = get_role_id(client, role_name, mount)
        click.echo(role_id)


    @cli.command()
    @click.argument('role_name')
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.pass_context
    def create_approle_secret_id(ctx, role_name, mount):
        """Create an approle's secret id from the role_name."""
        client = ctx.obj['client']
        secret_id = generate_secret_id(client, role_name, mount)
        click.echo(secret_id)


    @cli.command()
    @click.option('--role-name', required=True, help="AppRole name")
    @click.option('--mount', required=True, help="AppRole mount path")
    @click.option('--targeted-cluster-url', required=True,
                  help="Ingress targeted cluster url")
    @click.option('--secret-name', required=True,
                  help="Name of the secret in the target cluster")
    @click.option('--secret-namespace', required=True,
                  help="Namespace of the secret in the targeted cluster")
    @click.option('--kubeconfig', "kubeconfig_path", default=None, type=click.Path(exists=True))
    @click.pass_context
    def create_secret_in_targeted_cluster(
        ctx, role_name, mount, targeted_cluster_url, secret_name, secret_namespace,
        kubeconfig_path
    ):
        """Create the secret with approle id/secret-id in the targeted cluster'."""
        hvac_client = ctx.obj['client']
        secret_id = generate_secret_id(hvac_client, role_name, mount)

        from kubernetes import client, config
        from kubernetes.client.configuration import Configuration
        from json import loads
        from base64 import b64encode

        # Initialize connection to targeted kubernetes cluster
        client_config = Configuration()
        client_config.host = targeted_cluster_url

        # If kubeconfig is passed around we use it
        if kubeconfig_path:
            # For local clusters, no need
            client_config.verify_ssl = True

            # Configuration file holding the bearer token
            with open(kubeconfig_path, "r") as f:
                data = loads(f.read())
            client_config.api_key['authorization'] = data['bearerToken']
            client_config.api_key_prefix['authorization'] = 'Bearer'
        else:
            # otherwise, we assume we are working in the same cluster (e.g. local or
            # admin) as where this is running
            from os import environ

            # For local clusters, no need
            client_config.verify_ssl = False
            token_path = '/var/run/secrets/kubernetes.io/serviceaccount/token'
            with open(token_path, "r") as f:
                client_config.api_key['authorization'] = f.read()
            client_config.api_key_prefix['authorization'] = 'Bearer'

        api_client = client.ApiClient(configuration=client_config)

        # Create the approle secret structure (a simple key/value: id/secret-id)
        secret = client.V1Secret()
        secret.metadata = client.V1ObjectMeta(name=secret_name)
        secret.type = "Opaque"
        secret.data = {"id": b64encode(secret_id.encode()).decode()}

        # Actually create the secret in the targeted cluster
        api_instance = client.CoreV1Api(api_client=api_client)
        try:
            # We try to create the actual secret
            api_instance.create_namespaced_secret(namespace=secret_namespace, body=secret)
        except:
            # it can raise a conflict if it already exist, so we try to delete it first
            api_instance.delete_namespaced_secret(secret_name, secret_namespace)
            # Then we try to create it again
            api_instance.create_namespaced_secret(namespace=secret_namespace, body=secret)


    if __name__ == '__main__':
        cli()

  init-bao-cluster.sh: |
    #!/bin/bash

    set -x

    [ -z "${OPENBAO_ENDPOINT}" ] && \
      echo "<OPENBAO_ENDPOINT> env variable must be set" && exit 1
    [ -z "${OPENBAO_DEFAULT_TOKEN}" ] && \
      echo "<OPENBAO_DEFAULT_TOKEN> env variable must be set" && exit 1
    [ -z "${OPENBAO_NAMESPACE}" ] && \
      echo "<OPENBAO_NAMESPACE> env variable must be set" && exit 1
    [ -z "${POLICY_NAME}" ] && \
      echo "<POLICY_NAME> env variable must be set" && exit 1
    [ -z "${MOUNT}" ] && \
      echo "<MOUNT> env variable must be set" && exit 1
    [ -z "${ROLE}" ] && \
      echo "<ROLE> env variable must be set" && exit 1
    [ -z "${BAO_SCRIPT}" ] && \
      echo "<BAO_SCRIPT> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_URL}" ] && \
      echo "<CLUSTER_TARGET_URL> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_SECRET_NAME}" ] && \
      echo "<CLUSTER_TARGET_SECRET_NAME> env variable must be set" && exit 1
    [ -z "${CLUSTER_TARGET_SECRET_NAMESPACE}" ] && \
      echo "<CLUSTER_TARGET_SECRET_NAMESPACE> env variable must be set" && exit 1

    TEMP_DIR=$(mktemp -d)

    # FIXME: Move this part inside the dedicated swh-apps image (currently toolbox is
    # used)
    uv pip install hvac click kubernetes

    SCRIPT_ARGS=()
    SCRIPT_ARGS+=("--url" "${OPENBAO_ENDPOINT}")
    SCRIPT_ARGS+=("--token" "${OPENBAO_DEFAULT_TOKEN}")

    if [ ! -z "${NO_VERIFY_SSL}" ]; then
      SCRIPT_ARGS+=(--no-verify-ssl)
    fi

    ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" enable-secrets-engine ${MOUNT}

    # Then we create the policy for the future approle to create
    POLICY_FILENAME="${POLICY_NAME}.hcl"
    POLICY_FILE="${TEMP_DIR}/${POLICY_FILENAME}"
    # FIXME: For the migration period, let's add the create/update permissions.
    # Tol remove once the migration is done.
    cat > "${POLICY_FILE}" << EOF
      path "${MOUNT}/data/*" {
      capabilities = ["list", "read", "create", "update"]
    }

    path "${MOUNT}/metadata/*" {
      capabilities = ["list", "read", "create", "update"]
    }
    EOF

    ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-policy ${POLICY_NAME} ${POLICY_FILE}

    echo "Policy created:"
    cat "${POLICY_FILE}"

    # Finally we attach that policy to the new AppRole we create
    ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-approle \
      --mount ${MOUNT} \
      --policy-name ${POLICY_NAME} \
      ${ROLE}

    extra_args=()
    if [ ! -z ${CLUSTER_TARGET_KUBECONFIG} ]; then
      extra_args+=("--kubeconfig" "${CLUSTER_TARGET_KUBECONFIG}")
    fi

    ${BAO_SCRIPT} "${SCRIPT_ARGS[@]}" \
      create-secret-in-targeted-cluster \
      --role-name ${ROLE} \
      --mount ${MOUNT} \
      --targeted-cluster-url ${CLUSTER_TARGET_URL} \
      --secret-name ${CLUSTER_TARGET_SECRET_NAME} \
      --secret-namespace ${CLUSTER_TARGET_SECRET_NAMESPACE} \
      "${extra_args[@]}"
{{- end }}
