{{- if .Values.openbao.enabled }}
{{- $namespace := .Values.openbao.namespace -}}
{{- $secretName := .Values.openbao.secretNameRef -}}
{{- range $clusterTargetName, $clusterTargetConfig := .Values.openbao.deployments -}}
{{- $endpoint := $clusterTargetConfig.endpoint | default $.Values.openbao.endpoint -}}
{{- $clusterUrl := $clusterTargetConfig.url -}}
{{- $inCluster := $clusterTargetConfig.inCluster | default false -}}
{{- $verbose := $clusterTargetConfig.verbose | default $.Values.openbao.verbose | default false -}}
{{- $debug := $clusterTargetConfig.debug | default $.Values.openbao.debug | default false -}}
{{- $namespaces := $clusterTargetConfig.namespacesToManageInOpenbaoClientCluster |
                     default $.Values.openbao.namespacesToManageInOpenbaoClientCluster |
                     default list -}}
{{- $cronPeriod := $clusterTargetConfig.period | default $.Values.openbao.period -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: init-bao-cluster-{{ $clusterTargetName }}
  namespace: {{ $namespace }}
spec:
  schedule: {{ $cronPeriod | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: init-bao-cluster
              image: {{ $.Values.swh_openbao_image }}:{{ $.Values.swh_openbao_image_version }}
              command:
              {{- if $debug }}
              - /bin/sleep
              args:
              - infinity
              {{- else }}
              - /script/init-bao-cluster.sh
              {{- end }}
              env:
                - name: OPENBAO_ENDPOINT
                  value: {{ $endpoint }}
                - name: OPENBAO_NAMESPACE
                  value: {{ $clusterTargetName }}
                - name: ROLE
                  value: role-{{ $clusterTargetName }}
                - name: MOUNT
                  value: secrets-{{ $clusterTargetName }}
                - name: POLICY_NAME
                  value: openbao-policy-{{ $clusterTargetName }}
                - name: CLUSTER_TARGET_URL
                  value: {{ $clusterTargetConfig.url }}
                - name: CLUSTER_TARGET_SECRET_NAME
                  value: openbao-vso-auth-role-secret-id-secret
                - name: CLUSTER_TARGET_ROLE_ID_SECRET_NAME
                  value: openbao-vso-auth-role-id-secret
                - name: CLUSTER_TARGET_NAMESPACES
                  value: {{ $namespaces | join "," }}
                {{- if $verbose }}
                - name: DEBUG
                  value: "1"
                {{- end }}
                {{- if $clusterTargetConfig.noVerifySSL }}
                - name: NO_VERIFY_SSL
                  value: "1"
                {{- end }}
                {{- if not $inCluster }}
                - name: CLUSTER_TARGET_KUBECONFIG
                  value: /opt/swh/.kube/config
                {{- end }}
                - name: BAO_SCRIPT
                  value: /script/init_bao_cluster.py
              envFrom:
                # Secrets (OPENBAO_DEFAULT_TOKEN)
                - secretRef:
                    name: {{ $secretName }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: bao-script-utils
                mountPath: /script
              {{- if not $inCluster }}
              - name: kubeconfig
                mountPath: "/opt/swh/.kube/config"
                subPath: config
                readOnly: true
              {{- end }}
          volumes:
          - name: bao-script-utils
            configMap:
              name: bao-script-utils
              defaultMode: 0555
          {{- if not $inCluster }}
          - name: kubeconfig
            secret:
              secretName: {{ $clusterTargetName }}-cluster-config
          {{- end }}
          restartPolicy: OnFailure
{{ end }}
{{- end }}
