{{- if .Values.openbao.rbac.enabled -}}
{{- if not .Values.openbao.enabled }}
# Create the openbao namespace in cluster client of the main cluster running openbao.
# Thia also adds additional rbac authorization to allow that main cluster to write
# secrets (mainly the AppRole id and AppRole's associated secret id) and VaultAuth
# instances (so the client cluster can run VaultSecretsOperator and sync secrets through
# the VaultAuth [one per ns]).
---
apiVersion: v1
kind: Namespace
metadata:
  name: openbao
{{- end }}
# To authorize openbao cronjob orchestration to write secrets in the client cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  # Authorized to create and delete secret (for renewals)
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-secret-writer-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: openbao
roleRef:
  kind: ClusterRole
  name: openbao-secret-writer
  apiGroup: rbac.authorization.k8s.io
---
# To authorize openbao cronjob orchestration to write vaultauths in the client cluster

# vaultauth-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultauth-writer
rules:
- apiGroups: ["secrets.hashicorp.com"]
  resources: ["vaultauths"]
  verbs: ["create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vaultauth-writer-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: openbao
roleRef:
  kind: ClusterRole
  name: vaultauth-writer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
