{{- if .Values.openbao.rbac.enabled -}}
{{- if not .Values.openbao.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openbao
{{- end }}
# To authorize openbao cronjob orchestration to write secrets in the client cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  # Authorized to create and delete secret (for renewals)
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-secret-writer-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: openbao
roleRef:
  kind: ClusterRole
  name: openbao-secret-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: openbao-vso-auth
spec:
  method: appRole
  mount: secrets-{{ .Values.clusterName }}
  appRole:
    roleIdSecretRef:
      name: openbao-vso-auth-role-id-secret
      key: id
    secretIdSecretRef:
      name: openbao-vso-auth-role-secret-id-secret
      key: id
  allowedNamespaces:
    - "*"

{{- end }}
