{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.openbao.enabled (ne $clusterName "local-cluster") }}
{{- $namespace := .Values.openbao.namespace -}}
{{- $secretName := .Values.openbao.secretNameRef -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
{{ end }}
