---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  # PAT with the following rights: 
  # api
  # read_user
  # API URL (Staging or prod)
  RENOVATE_ENDPOINT: "https://gitlab-staging.swh.network/api/v4"

  # Gitlab PAT 
  RENOVATE_TOKEN: glpat-Co1A7DItP90stnkiIxZcq286MQp1OmMwCA.01.0y0dm2l9s

  # Acceptance of the TOS (Terms of Service) Mend
  MEND_RNV_ACCEPT_TOS: "y"

  # Public license (limited to 10 copies) or a personal license
  MEND_RNV_LICENSE_KEY: "eyJuYW1lIjoiU29mdHdhcmUgSGVyaXRhZ2UgU1dIIiwiZW1haWwiOiJzeXNvcCtyZW5vdmF0ZUBzb2Z0d2FyZWhlcml0YWdlLm9yZyIsImNvbXBhbnkiOiJTV0gifQ==.304402202d2a5f1547c656cce5c7f7d839ab7ebb3c6b8249e9bb1dcec76659967b5c5be8022004dacc4af9d91ea2b272cc1cb00b8d5cf7db64f5768cf349d352185c98dd70ff"
  
  # Personal user token for github for fetching changelogs
  GITHUB_COM_TOKEN: "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"