{{ if .Values.volumes.enabled -}}
{{- range $pvName, $pvConfig := .Values.volumes.persistentVolumes }}
{{- if or (not (hasKey $pvConfig "enabled")) (get $pvConfig "enabled") -}}
{{- $appName := $pvConfig.appName -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $pvName }}
  {{- if $appName }}
  labels:
    app: {{ $appName }}
  {{- end }}
spec:
  {{- toYaml $pvConfig.spec | nindent 2 }}
{{ end }}
{{ end }}
{{ end }}
