{{- $clusterName := .Values.clusterName -}}
{{- $namespace := .Values.namespace -}}
{{- with .Values.checkerDeposit }}
{{- if and .enabled (ne $clusterName "local-cluster") -}}
{{- $secrets := list -}}
{{- $secretsDict := include "swh.secrets.dictFromDeploymentConfig"
     (dict "deploymentConfig" .
           "Values" $.Values) | fromYaml | default dict -}}
{{- range $name, $secretConfig := $secretsDict -}}
  {{- $secretName := dig "secretKeyRef" "" $secretConfig -}}
  {{- if $secretName }}
    {{- $secrets = append $secrets (list $secretName $namespace) -}}
  {{- end }}
{{- end }}

{{- if .sentry.enabled -}}
  {{- $secretName := dig "secretKeyRef" "" .sentry -}}
  {{- if $secretName }}
    {{- $secrets = append $secrets (list $secretName $namespace) -}}
  {{- end }}
{{- end }}

{{ range $secret := uniq $secrets }}
  {{ $secretName := first $secret }}
  {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}

{{ end }}
{{ end }}
{{ end }}
