{{ if .Values.svix.enabled -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- if or (not (hasKey $svixConfiguration "enabled")) (get $svixConfiguration "enabled") -}}
{{- $ns := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- $affinity := $svixConfiguration.affinity | default $.Values.svix.affinity -}}
{{- $appName := print $svixName "-ingress" -}}
{{- $whitelistSourceRange := $svixConfiguration.ingress.whitelistSourceRange | default list -}}
{{- $whitelistSourceRangeCSV := join "," $whitelistSourceRange -}}
{{- $ingressAnnotations := $svixConfiguration.ingress.annotations -}}
{{- $ingressClassName := $svixConfiguration.ingress.className -}}
{{- $ingressHost := $svixConfiguration.ingress.host -}}
{{- $createTLS := $svixConfiguration.ingress.createTLS }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ $ns }}
  name: {{ $appName }}
  annotations:
  {{- if $ingressAnnotations }}
    {{- toYaml $ingressAnnotations | nindent 4 }}
  {{- end }}
  {{- if $whitelistSourceRangeCSV }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ $whitelistSourceRangeCSV }}
  {{- end }}
spec:
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  rules:
  - host: {{ $ingressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svix
            port:
              number: 8071
  {{- if $createTLS }}
  tls:
  - hosts:
    - {{ $ingressHost }}
    secretName: {{ $svixName }}-crt
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
