{{ if .Values.svix.enabled -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- $ns := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- $appName := print $svixName "-server" -}}
{{- $podSelectorPolicy := $svixConfiguration.redis.podSelectorPolicy
      | default $.Values.svix.redis.podSelectorPolicy
      | default dict -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-{{ $svixName }}-ingress
  namespace: {{ $ns }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: all-access-{{ $svixName }}-http
  namespace: {{ $ns }}
spec:
  podSelector:
    matchLabels:
      app: {{ $appName }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8071
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $svixName }}-access-redis
  namespace: {{ $ns }}
spec:
  podSelector:
    matchLabels:
{{- if $podSelectorPolicy }}
      {{ toYaml $podSelectorPolicy -}}
{{- else }}
      app: redis-{{ $svixName }}
{{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ $appName }}
        {{- if $podSelectorPolicy }}
        - podSelector:
            matchLabels:
              {{- toYaml $podSelectorPolicy | nindent 14 -}}
        {{- end }}
      ports:
        - protocol: TCP
          port: 6379
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 9121
{{ if $svixConfiguration.postgres.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $svixName }}-access-postgres
  namespace: {{ $ns }}
spec:
  podSelector:
    matchLabels:
      app: {{ $svixName }}-postgres
  ingress:
    - from:
        - podSelector:
            matchLabels:
             app: {{ $appName }}
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
{{- end }}
{{- end }}
