{{ if .Values.svix.enabled -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{ $namespace := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- if or (not (hasKey $svixConfiguration "enabled")) (get $svixConfiguration "enabled") -}}
{{- $postgres := $svixConfiguration.postgres | default $.Values.svix.postgres | default dict -}}
{{- $cleanupExpiredMessages := $postgres.cleanupExpiredMessages | default (dict "enabled" "false") -}}
{{- if $cleanupExpiredMessages.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: svix-script-utils
  namespace: {{ $namespace }}
data:

  cleanup-expired-messages.sql: |
    -- Cleanup svix database message* table rows whose expiration is older
    -- than a given period (adapt the period according to the need).

    select now();

    -- Cleanup messages older than x days (adapt this if need be). The current
    -- model has on cascade delete constraints on some tables but not all of
    -- them

    DELETE FROM message
    WHERE created_at < NOW() - INTERVAL '14 days';

    DELETE FROM messageattempt
    WHERE ended_at < NOW() - INTERVAL '14 days';

    SELECT
      NOW(),
      (SELECT COUNT(*) FROM message) AS messages,
      (SELECT COUNT(*) FROM messagecontent) AS messagecontents,
      (SELECT COUNT(*) FROM messageattempt) AS messageattempts,
      (SELECT COUNT(*) FROM messagedestination) AS messagedestinations;

  cleanup-expired-messages.sh: |
    #!/bin/bash

    # This ensures the necessary environment variables to access the database
    # are provided. And then pursues to run the ${SQL_CLEANUP_FILE}

    # Uses mandatory env variables:
    # - SVIX_DB_HOST
    # - SVIX_DB_NAME
    # - SVIX_DB_USER
    # - SVIX_DB_PASS
    # - SQL_CLEANUP_FILE

    set -e

    [ -z "${SVIX_DB_HOST}" ] && \
      echo "<SVIX_DB_HOST> env variable must be set" && exit 1
    [ -z "${SVIX_DB_NAME}" ] && \
      echo "<SVIX_DB_NAME> env variable must be set" && exit 1
    [ -z "${SVIX_DB_USER}" ] && \
      echo "<SVIX_DB_USER> env variable must be set" && exit 1
    [ -z "${SVIX_DB_PASS}" ] && \
      echo "<SVIX_DB_PASS> env variable must be set" && exit 1
    [ -z "${SQL_CLEANUP_FILE}" ] && \
      echo "<SQL_CLEANUP_FILE> env variable must be set" && exit 1

    [ ! -f "${SQL_CLEANUP_FILE}" ] && \
      echo "<$SQL_CLEANUP_FILE> filepath does not exist."

    connstring="host=${SVIX_DB_HOST} user=${SVIX_DB_USER} dbname=${SVIX_DB_NAME} password=${SVIX_DB_PASS}"
    time psql \
      --no-psqlrc \
      --echo-all \
      --file="${SQL_CLEANUP_FILE}" \
      --set=ON_ERROR_STOP=1 \
      "${connstring}"

{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
