{{ if .Values.svix.enabled -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- $ns := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- $appName := print $svixName "-server" -}}
{{ if $svixConfiguration.postgres.enabled -}}
{{- $appPostgresqlName := print $svixName "-postgres" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appPostgresqlName }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appPostgresqlName }}
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
{{- end }}
{{ if $svixConfiguration.redis.enabled -}}
{{- $appRedisName := print $svixName "-redis" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appRedisName }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appRedisName }}
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svixName }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appName }}
  ports:
    - port: 8071
      targetPort: 8071
      name: svix
{{- end }}
{{- end }}
