{{ if .Values.svix.enabled -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- if or (not (hasKey $svixConfiguration "enabled")) (get $svixConfiguration "enabled") -}}
{{ $redisDsn := $svixConfiguration.redis.dsn | default "redis" -}}
{{ $redisFullDsn := print "redis://" $redisDsn ":6379" }}
{{ $redisQueueType := $svixConfiguration.redis.queueType | default "redis" -}}
{{ $redisCacheType := $svixConfiguration.redis.cacheType | default "redis" -}}
{{ $postgresDsn := $svixConfiguration.postgres.dsn | default "postgres" -}}
{{ $postgresFullDsn := print "postgresql://$(SVIX_DB_USER):$(SVIX_DB_PASS)@" $postgresDsn -}}
{{ $ns := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{ $affinity := $svixConfiguration.affinity | default $.Values.svix.affinity -}}
{{ $appName := print $svixName "-server" -}}
{{ $version := $svixConfiguration.version | default $.Values.svix.version -}}
{{ $tlsDisable := $svixConfiguration.tlsDisable | default $.Values.svix.tlsDisable -}}
{{ $whitelistSubnets := $svixConfiguration.whitelistSubnets | default $.Values.svix.whitelistSubnets -}}
{{- $priorityClassName := $.Values.svix.priorityClassName -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $ns }}
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ $svixConfiguration.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if and $.Values.podPriority.enabled $priorityClassName }}
      priorityClassName: {{ $ns }}-{{ $priorityClassName }}
      {{- end }}
      containers:
        - name: svix-server
          resources:
            requests:
              memory: {{ $svixConfiguration.requestedMemory | default "512Mi" }}
              cpu: {{ $svixConfiguration.requestedCpu | default "500m" }}
          image: svix/svix-server:{{ $version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8071
              name: svix
          readinessProbe:
            httpGet:
              path: /
              port: svix
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: svix
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 30
          env:
            - name: SVIX_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: svix-server-secrets
                  key: SVIX_JWT_SECRET
            - name: SVIX_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: svix-server-secrets
                  key: APP_DB_PASS
            - name: SVIX_DB_USER
              valueFrom:
                secretKeyRef:
                  name: svix-server-secrets
                  key: APP_DB_USER
            - name: WAIT_FOR
              value: "true"  # We want to wait for the default services
            - name: SVIX_QUEUE_TYPE
              value: {{ $redisQueueType }}
            - name: SVIX_CACHE_TYPE
              value: {{ $redisCacheType }}
            - name: SVIX_REDIS_DSN
              value: {{ $redisFullDsn | quote }}
            - name: SVIX_DB_DSN
              value: {{ $postgresFullDsn | quote }}
            {{- if $tlsDisable }}
            - name: SVIX_DANGEROUS_DISABLE_TLS_VERIFICATION
              value: "true"
            {{- end }}
            {{- if $whitelistSubnets }}
            - name: SVIX_WHITELIST_SUBNETS
              value: {{ print "[" (join "," $whitelistSubnets) "]" | quote }}
            {{- end }}
{{- end }}
{{- end }}
{{- end }}
