{{- if .Values.svix.enabled }}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- $namespace := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- $secretName := $svixConfiguration.secretsRef | default $.Values.svix.secretsRef -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
{{ end }}
{{ end }}
