{{- if .Values.svix.enabled }}
{{- $clusterName := .Values.clusterName -}}
{{- $secrets := list -}}
{{- range $svixName, $svixConfiguration := .Values.svix.deployments -}}
{{- $namespace := $svixConfiguration.namespace | default $.Values.svix.namespace -}}
{{- $secretName := $svixConfiguration.secretsRef | default $.Values.svix.secretsRef -}}
{{- $secrets = append $secrets (list $secretName $namespace) -}}
{{ end }}

{{ range $secret := uniq $secrets }}
{{ $secretName := first $secret }}
{{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
{{ end }}
{{ end }}
