{{ if .Values.kafka.enabled -}}
{{- range $clusterName, $clusterConfig := .Values.kafka.deployments -}}
{{- if (ne false $clusterConfig.enabled) -}}
{{- $namespace := $clusterConfig.namespace | default $.Values.kafka.namespace -}}
{{- $clusterName = $clusterConfig.clusterName | default $clusterName -}}
{{- $clusterTopicsEntries := dig "topics" "entries" dict $clusterConfig -}}
{{- $defaultTopicsConfig := dig "topics" "defaultConfig" dict $clusterConfig | default dict -}}
{{- range $topicName, $topicConfig := $clusterTopicsEntries -}}
{{- $specificTopicConfig := dig "config" dict $topicConfig -}}
{{- $enrichedTopicConfig := mustMerge $specificTopicConfig $defaultTopicsConfig -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topicName | replace "_" "-" }}
  namespace: {{ $namespace }}
  labels:
    strimzi.io/cluster: {{ $clusterName }}
spec:
  topicName: {{ $topicName }}
  partitions: {{ get $enrichedTopicConfig "partitions" | default 1 }}
  replicas: {{ get $enrichedTopicConfig "replicas" | default 1 }}
  {{- if $enrichedTopicConfig.extraConfig }}
  config:
    {{- toYaml $enrichedTopicConfig.extraConfig | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
