{{ if .Values.kafka.enabled -}}
{{- range $clusterName, $clusterConfig := .Values.kafka.deployments -}}
{{- if or (not (hasKey $clusterConfig "enabled")) (get $clusterConfig "enabled") -}}
{{- range $topicName, $topicConfig := $clusterConfig.topics -}}
{{- $specificTopicConfig := $topicConfig.config | default dict -}}
{{- $defaultTopicConfig := $.Values.kafka.default.topics.config | default dict -}}
{{- $enrichedTopicConfig := mustMerge $specificTopicConfig $defaultTopicConfig -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topicName | replace "_" "-" }}
  namespace: {{ $.Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ $clusterName }}
spec:
  topicName: {{ $topicName }}
  partitions: {{ get $topicConfig "partitions" | default $.Values.kafka.default.topics.partitions | default 1 }}
  replicas: {{ get $topicConfig "replicas" | default $.Values.kafka.default.topics.replicas | default 1 }}
  {{- if $enrichedTopicConfig }}
  config:
    {{- toYaml $enrichedTopicConfig | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
