{{- $clusterName := .Values.clusterName -}}
{{- if and .Values.kafka.enabled (ne $clusterName "local-cluster") }}
  {{- $secrets := list -}}
  {{- range $clusterName, $clusterConfig := .Values.kafka.deployments -}}
    {{- if (ne false $clusterConfig.enabled) -}}
      {{- $namespace := $clusterConfig.namespace | default $.Values.kafka.namespace -}}
      {{- range $userName, $userConfig := $clusterConfig.users -}}
        {{- $secretRef := dig "secret" "ref" "" $userConfig -}}
        {{- if $secretRef }}
          {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- range $secret := uniq $secrets }}
    {{ $secretName := first $secret }}
    {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{- end }}
