cloudnativePg:
  database:
    # default locale for swh modules
    # for Django applications use `en_US.utf8`
    localeCollate: 'C.UTF-8'
    localeCType: 'C.UTF-8'
  pooler:
    enabled: false
    mode: session
    types: []
  backup:
    compression: gzip
    # Let's use the new barman plugin
    # It's required for future cnpg version > 1.26
    systemType: plugin
    # 1 week retention for staging
    retention: 7d
    s3Config:
      # path: <bucket-name>/<cluster-name>/<namespace>/<db-name>
      # Note: Don't let the trailing slash in the path configuration, otherwise, backups
      # won't get cleaned up
      # See: https://github.com/EnterpriseDB/barman/issues/944
      path: s3://backup-cnpg/archive-staging-rke2/cnpg
      url: https://minio.admin.swh.network
      secretName: cnpg-minio-secret
      accessKey: MINIO_ACCESS_KEY
      secretKey: MINIO_SECRET_KEY
  superuserAccessEnabled: false
  storage:
    storageClass: local-persistent
    size: 1Gi
  services:
    disabledDefaultServices:
      - "r"
      - "ro"
  roles:
  - name: guest
    ensure: present
    comment: read-only user
    login: true
    connectionLimit: -1
    passwordSecret:
      name: swh-postgresql-guest-secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/db"
            operator: In
            values:
            - "true"

rabbitmq:
  storageVolume:
    class: local-persistent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

elasticsearch:
  nodeSelector:
    "swh/elasticsearch": "true"

cassandra:
  nodeAffinityLabels:
    "swh/cassandra": "true"

kafka:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

svix:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: svix-server
            operator: In
            values:
            - "true"
