cloudnativePg:
  enableSuperuserAccess: true
  storage:
    storageClass: local-persistent
    size: 1Gi
  roles:
    - name: guest
      ensure: present
      comment: Guest
      login: true
      connectionLimit: -1
      inherit: true
      passwordSecret:
        name: swh-postgresql-guest-secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/db"
            operator: In
            values:
            - "true"

rabbitmq:
  storageVolume:
    class: local-persistent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

elasticsearch:
  nodeSelector:
    "swh/elasticsearch": "true"

cassandra:
  nodeAffinityLabels:
    "swh/cassandra": "true"

kafka:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

svix:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: svix-server
            operator: In
            values:
            - "true"
