cloudnativePg:
  pooler:
    enabled: false
    mode: session
    types: []
  backup:
    compression: gzip
    s3Config:
      path: s3://backup-cnpg/archive-staging-rke2
      url: https://minio.admin.swh.network
      accessKey: MINIO_ACCESS_KEY
      secretKey: MINIO_SECRET_KEY
  enableSuperuserAccess: false
  storage:
    storageClass: local-persistent
    size: 1Gi
  roles:
    - name: guest
      ensure: present
      comment: Guest
      login: true
      connectionLimit: -1
      inherit: true
      passwordSecret:
        name: swh-postgresql-guest-secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/db"
            operator: In
            values:
            - "true"

rabbitmq:
  storageVolume:
    class: local-persistent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

elasticsearch:
  nodeSelector:
    "swh/elasticsearch": "true"

cassandra:
  nodeAffinityLabels:
    "swh/cassandra": "true"

kafka:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backend"
            operator: In
            values:
            - "true"

svix:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: svix-server
            operator: In
            values:
            - "true"
