{{- with .Values.gitlabRunner }}
{{- if .enabled }}
{{- $namespace := .namespace -}}
{{- $secretName := dig "runners" "secret" "" . | default "" -}}
{{- if $secretName }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $.Values.clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
{{ end }}
{{ end }}
{{ end }}
