namespace: swh

certManager:
  defaultClusterIssuer: letsencrypt-production-gandi

prometheus:
  address: http://prometheus-operated.cattle-monitoring-system:9090
  scrapingConfig:
    globalLabels:
      release: rancher-monitoring

SwhStatusUrl:
  server_url: https://status.softwareheritage.org/
  json_path: 1.0/status/578e5eddcdc0cc7951000520

sentry:
  enabled: true

defaultLoggingConfig:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: INFO
      stream: ext://sys.stdout
  formatters:
    default:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      # This format is only used to pull the variables that are stuck in the json dicts
      format: "[%(asctime)s: %(levelname)s/%(processName)s-%(process)d %(threadName)s(%(pathname)s:%(lineno)s:%(funcName)s)]%(name)s %(message)s"
  loggers:
    swh:
      level: INFO
    swh.core.statsd:
      level: INFO
  root:
    handlers:
      - console
    level: INFO

rpcGunicornLoggingConfig:
  disable_existing_loggers: true
  filters:
    throttle_accesslog:
      interval: 60
      status_codes: [200, 400]
  loggers:
    azure: # Don't log each call to azure in the objstorage/storage
      level: WARN
    gunicorn:
      level: INFO
    gunicorn.error:
      level: INFO
    gunicorn.access:
      level: WARN
      filters: [throttle_accesslog]
      handlers:
        - console

tmpEphemeralStorage:
  claimTemplate:
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: ephemeral-volume
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 100Gi # no effects

memcached:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/memcached"
            operator: In
            values:
            - "true"

checkerDeposit:
  sentry:
    enabled: true
    secretKeyRef: checker-deposit-sentry-secret
    secretKeyName: checker-deposit-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/deposit"
            operator: In
            values:
            - "true"

storageReplayer:
  sentry:
    enabled: true
    secretKeyRef: storage-replayer-sentry-secrets
    secretKeyName: sentry-dsn
  cassandra:
    keySpace: swh
    consistencyLevel: LOCAL_QUORUM
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "swh/replayer"
              operator: In
              values:
              - "true"

cookers:
  maxBundleSize: 1073741824
  sentry:
    enabled: true
    secretKeyRef: sentry-settings-for-celery-tasks

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/cooker"
            operator: In
            values:
            - "true"

loaderMetadata:
  dnsConfigurationRef: dnsConfiguration
  sentry:
    enabled: true
    secretKeyRef: loader-metadata-sentry-secret
    secretKeyName: loader-metadata-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/loader-metadata"
            operator: In
            values:
            - "true"

indexers:
  sentry:
    enabled: true
    secretKeyRef: indexer-sentry-secret
    secretKeyName: indexer-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/indexer"
            operator: In
            values:
            - "true"

loaders:
  dnsConfigurationRef: dnsConfiguration
  sentry:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/loader"
            operator: In
            values:
            - "true"

listers:
  sentry:
    enabled: true
    secretKeyRef: sentry-settings-for-celery-tasks
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/lister"
            operator: In
            values:
            - "true"

graphql:
  sentry:
    enabled: true
    secretKeyRef: graphql-sentry-secret
    secretKeyName: graphql-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/rpc
            operator: In
            values:
            - "true"

storage:
  sentry:
    enabled: true
    secretKeyRef: storage-sentry-secret
    secretKeyName: storage-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/storage
            operator: In
            values:
            - "true"

scheduler:
  sentry:
    enabled: true
    secretKeyRef: scheduler-sentry-secrets
    secretKeyName: sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/scheduler
            operator: In
            values:
            - "true"

vault:
  sentry:
    enabled: true
    secretKeyRef: swh-vault-sentry-secret
    secretKeyName: sentry-dsn
  extraConfig:
    smtp:
      host: smtp.inria.fr
      port: 25
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/rpc
            operator: In
            values:
            - "true"

# List of django apps the webapp must declare
webDjangoApps:
  - swh.web.add_forge_now
  - swh.web.archive_coverage
  - swh.web.badges
  - swh.web.banners
  - swh.web.deposit
  - swh.web.inbound_email
  - swh.web.jslicenses
  - swh.web.mailmap
  - swh.web.metrics
  - swh.web.save_code_now
  - swh.web.save_origin_webhooks
  - swh.web.vault
  - swh.web.provenance
  - swh.web.save_bulk
  - swh.web.alter
  - swh.web.admin
  - swh.web.vulns

# List of minimal django apps necessary for the webhook web instance
webDjangoAppsMinimal:
  - swh.web.save_origin_webhooks

web:
  migrations:
    enabled: true
  sentry:
    enabled: true
    secretKeyRef: web-sentry-secret
    secretKeyName: web-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/web
            operator: In
            values:
            - "true"
  ingress:
    extraAnnotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 100M

deposit:
  migrations:
    enabled: true
  sentry:
    enabled: true
    secretKeyRef: deposit-sentry-secret
    secretKeyName: deposit-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/deposit
            operator: In
            values:
            - "true"
  ingress:
    extraAnnotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 4G
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/client-body-buffer-size: 128K
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

indexerStorage:
  sentry:
    enabled: true
    secretKeyRef: indexer-storage-sentry-secret
    secretKeyName: sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/rpc
            operator: In
            values:
            - "true"

search:
  sentry:
    enabled: true
    secretKeyRef: swh-search-sentry-secret
    secretKeyName: sentry-dsn
  rpc:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: swh/rpc
              operator: In
              values:
              - "true"
  journalClients:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: swh/journal_client
              operator: In
              values:
              - "true"

scrubber:
  sentry:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/scrubber"
            operator: In
            values:
            - "true"

toolbox:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/toolbox"
            operator: In
            values:
            - "true"

ingestion_benchmarks:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/toolbox"
            operator: In
            values:
            - "true"
  workers:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "swh/toolbox"
              operator: In
              values:
              - "true"

objstorage:
  port: 5003
  sentry:
    enabled: true
    secretKeyRef: objstorage-sentry-secret
    secretKeyName: sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/objstorage
            operator: In
            values:
            - "true"

webhooks:
  sentry:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/webhooks
            operator: In
            values:
            - "true"

statsd_exporter:
  enabled: true

counters:
  sentry:
    enabled: true
    secretKeyRef: counters-sentry-secret
    secretKeyName: counters-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/counters
            operator: In
            values:
            - "true"
  rpc:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: swh/rpc
              operator: In
              values:
              - "true"
  journalClient:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: swh/journal_client
              operator: In
              values:
              - "true"

objstorageReplayer:
  sentry:
    enabled: true
    secretKeyRef: objstorage-replayer-sentry-secret
    secretKeyName: sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/replayer"
            operator: In
            values:
            - "true"

dnsConfiguration:
  ndots: 1
  overrideSearch: true
#  extraSearch:
#    - internal.softwareheritage.org
#  nameservers: [ 10.43.0.10 ]
#  policy: None

cassandraChecks:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/journal_client
            operator: In
            values:
            - "true"

storageBackfiller:
  sentry:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/backfiller"
            operator: In
            values:
            - "true"

alter:
  sentry:
    enabled: true
    # secretKeyRef: common-secrets
    # secretKeyName: alter-sentry-dsn
  deployment:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "swh/alter"
              operator: In
              values:
              - "true"

provenance:
  sentry:
    enabled: true
    secretKeyRef: common-secrets
    secretKeyName: provenance-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/provenance"
            operator: In
            values:
            - "true"

graph:
  imageVersion: "20260625.1"
  sentry:
    enabled: true
    secretKeyRef: common-secrets
    secretKeyName: graph-sentry-dsn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/graph"
            operator: In
            values:
            - "true"

coarNotify:
  sentry:
    enabled: true
    secretKeyRef: coarnotify-sentry-secret
    secretKeyName: coarnotify-sentry-dsn

  deployment:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "swh/frontend"
              operator: In
              values:
              - "true"

journalWriterMirrorConfiguration:
  brokersConfigurationRef: kafkaBrokers
  clientId: swh.alter.removals.${HOSTNAME}
  prefix: swh.journal.mirror-notifications
  producerConfig:
    message.max.bytes: 1000000000

datasetsGenerator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: swh/datasets
            operator: In
            values:
            - "true"

webAlter:
  email_setup:
    backend: "django.core.mail.backends.smtp.EmailBackend"
    host: smtp.inria.fr
    port: 25
    default_from_email: "no-reply@softwareheritage.org"
  alter_settings:
    block_disposable_email_domains: false

# Graph main directory path to write or read graph data from (can be published in s3
# without sensitive data). It will be the main folder onto which dataset named folder
# (/srv/dataset/YYYY-MM-DD/) will be created with the data. The sensitive data will be on
# another folder (/srv/dataset-sensitive/YYYY-MM-DD)
graphDirectoryPath: /srv/dataset

staticWebsites:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "swh/static-websites"
            operator: In
            values:
            - "true"
