{{ if .Values.cloudnativePg.enabled -}}
{{- $appName := print .Values.clusterName "-cnpg-barman-plugin" -}}
{{- $prune := .Values.cloudnativePg.argocdApplication.prune | default .Values.defaultPrune -}}
{{- $selfHeal := .Values.cloudnativePg.argocdApplication.selfHeal | default .Values.defaultSelfHeal -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  revisionHistoryLimit: 2
  project: {{ .Values.defaultProject }}
  source:
    repoURL: 'https://github.com/cloudnative-pg/plugin-barman-cloud'
    targetRevision: v{{ .Values.cloudnativePg.barmanPluginVersion }}
    path: .
    directory:
      include: 'manifest.yaml'
  destination:
    server: {{ .Values.clusterUrl }}
    namespace: {{ .Values.cloudnativePg.namespace | default "cnpg-system" | quote }}
  syncPolicy:
    {{- if or $prune $selfHeal }}
    automated:
      {{- if $prune }}
      prune: {{ $prune }}
      {{- end }}
      {{- if $selfHeal }}
      selfHeal: {{ $selfHeal }}
      {{- end }}
    {{- end }}
    syncOptions:
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jqPathExpressions:
        - .spec.duration
        - .spec.renewBefore
{{ end }}
