{{- $clusterName := .Values.clusterName}}
{{- with .Values.kafkabackup }}
{{- if .enabled }}
{{- $sshSecretKeyName := .ssh.secretKeyName -}}
{{- $storageSecretsName := .storageSecretsName -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $sshSecretKeyName }}-vss
  namespace: {{ .namespace }}
spec:
  destination:
    create: true
    name: {{ $sshSecretKeyName }}
    overwrite: true
    type: kubernetes.io/ssh-auth
  mount: secrets-{{ $clusterName }}
  path: {{ $sshSecretKeyName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $storageSecretsName }}-vss
  namespace: {{ .namespace }}
spec:
  destination:
    create: true
    name: {{ $storageSecretsName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $storageSecretsName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
{{ end }}
{{ end }}
