{{- $clusterName := .Values.clusterName -}}
{{- with .Values.keycloak }}
{{- $namespace := .namespace -}}
{{- if and .enabled (ne $clusterName "local-cluster") }}
  {{- $secrets := list -}}
  {{- $secretRef := dig "adminSecret" "ref" "" . -}}
  {{- if $secretRef }}
    {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
  {{- end }}
  {{- $secretRef := dig "database" "secret" "ref" "" . -}}
  {{- if $secretRef }}
    {{- $secrets = concat $secrets (list (list $secretRef $namespace)) -}}
  {{- end }}

  {{- range $secret := uniq $secrets }}
    {{- $secretName := first $secret -}}
    {{- $namespace := last $secret -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $.Values.vaultAuthRef }}
  {{- end }}
{{ end }}
{{- end }}
