{{ define "swh.storageReplayer.configmap" }}
{{- $journalClientConfigurationRef := .deploymentConfig.journalClientConfigurationRef -}}
{{- $journalClientConfiguration := required (print "journalClientConfigurationRef <" $journalClientConfigurationRef "> not found in storageReplayer <" .deploymentName ">  configuration") (get .Values $journalClientConfigurationRef) -}}
{{- $journalClientOverrides := deepCopy (get .deploymentConfig "journalClientOverrides" | default dict) -}}
{{- $errorReporterConfig := .deploymentConfig.error_reporter -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-replayer-configuration-{{ .deploymentName }}-template
  namespace: {{ $.Values.namespace }}
data:
  config.yml.template: |
    {{- include "swh.storageConfiguration"
      (dict "configurationRef" .Values.storageReplayer.storageConfigurationRef
            "Values" .Values) | nindent 4 }}
    {{- include "swh.journalClientConfiguration"
      (dict "serviceType" "journal_client"
                          "configurationRef" $journalClientConfigurationRef
                          "overrides" $journalClientOverrides
                          "Values" .Values) | nindent 4 }}
    {{- if and $errorReporterConfig (or (not (hasKey $errorReporterConfig "enabled"))
                                        (get $errorReporterConfig "enabled")) -}}
    {{ $_ := unset $errorReporterConfig "enabled" }}
    replayer:
      error_reporter:
      {{- range $option, $value := $errorReporterConfig }}
        {{ $option }}: {{ $value }}
      {{- end }}
    {{- end }}

{{ end }}

{{/*
  Configure the autoscaling for a deployment type
*/}}
{{- define "swh.storageReplayer.autoscaling" -}}
{{- $journalClientConfigurationRef := .deploymentConfig.journalClientConfigurationRef -}}
{{- $journalClientBaseConfiguration := required (print "journalClientConfigurationRef <" $journalClientConfigurationRef "> not found in storageReplayer <" .deploymentName ">  configuration") (get .Values $journalClientConfigurationRef) -}}
{{- $journalClientOverrides := deepCopy (get .deploymentConfig "journalClientOverrides" | default dict) -}}
{{- $journalClientConfiguration := deepCopy $journalClientBaseConfiguration }}
{{- $journalClientConfiguration := mustMergeOverwrite $journalClientConfiguration $journalClientOverrides -}}
{{- $brokersConfigurationRef := $journalClientConfiguration.brokersConfigurationRef -}}
{{- $brokers := get .Values $brokersConfigurationRef -}}
{{- $_ := set $journalClientConfiguration "brokers" $brokers -}}
{{- $_ := unset $journalClientConfiguration "brokersConfigurationRef" -}}
{{- $_ := required (print "<group_id> property is mandatory in <" $journalClientConfiguration "> map") (get $journalClientConfiguration "group_id") -}}
{{- include "swh.keda.kafkaAutoscaler"
      (dict "name"                     (print "storage-replayer-" .deploymentName)
            "kafkaConfiguration"       $journalClientConfiguration
            "autoscalingConfiguration" .deploymentConfig.autoScaling
            "Values"                   .Values) -}}

{{- end -}}
