{{ if .Values.storageReplayer.enabled -}}
{{- range $deployment, $deploymentConfig := .Values.storageReplayer.deployments -}}
{{- $deploymentConfig = mustMerge (deepCopy $deploymentConfig) (deepCopy $.Values.storageReplayer) -}}
{{- if (ne false $deploymentConfig.enabled) -}}
{{ include "swh.storageReplayer.configmap" (dict "deployment" $deployment
                                                 "deployment_config" $deploymentConfig
                                                 "Values" $.Values) }}
{{- end -}}
{{ end -}}
{{ end }}
