{{ if .Values.storageReplayer.enabled -}}
{{- range $deploymentName, $deploymentConfig := .Values.storageReplayer.deployments -}}
{{- if (ne false $deploymentConfig.enabled) -}}
{{- $deploymentConfig := include "swh.mergeDeploymentConfig"
      (dict "deploymentConfig" $deploymentConfig
            "topConfig"        $.Values.storageReplayer) | fromYaml -}}
{{ include "swh.storageReplayer.configmap" (dict "deploymentName"   $deploymentName
                                                 "deploymentConfig" $deploymentConfig
                                                 "Values"           $.Values) }}
{{- end -}}
{{ end -}}
{{ end }}
