{{ if .Values.storageReplayer.enabled -}}
{{- range $deploymentName, $deploymentConfig := .Values.storageReplayer.deployments -}}
{{- $deploymentConfig = mustMerge (deepCopy $deploymentConfig) (deepCopy $.Values.storageReplayer) -}}
{{- if (ne false $deploymentConfig.enabled) -}}
{{ include "swh.storageReplayer.configmap" (dict "deploymentName"   $deploymentName
                                                 "deploymentConfig" $deploymentConfig
                                                 "Values"           $.Values) }}
{{- end -}}
{{ end -}}
{{ end }}
