{{ if .Values.storageReplayer.enabled -}}
{{- $storageUtilsToChecksum := include (print $.Template.BasePath "/utils/backend-utils.yaml") . -}}
{{- range $deployment, $deploymentConfig := .Values.storageReplayer.deployments -}}
{{- if (ne false $deploymentConfig.enabled) -}}
{{- $deploymentConfig = mustMerge (deepCopy $deploymentConfig) (deepCopy $.Values.storageReplayer) -}}
{{- $configurationToChecksum := include "swh.storageReplayer.configmap"
  (dict "deployment" $deployment
        "deployment_config" $deploymentConfig
        "Values" $.Values) -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: storage-replayer-{{ $deployment }}
  labels:
    app: storage-replayer-{{ $deployment }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: storage-replayer-{{ $deployment }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: storage-replayer-{{ $deployment }}
      annotations:
        checksum/config: {{ $configurationToChecksum | sha256sum }}
        checksum/config_utils: {{ $storageUtilsToChecksum | sha256sum }}
    spec:
      {{- if $deploymentConfig.affinity }}
      affinity:
        {{- toYaml $deploymentConfig.affinity | nindent 8 }}
      {{- end }}
      {{- if and $.Values.podPriority.enabled $deploymentConfig.priorityClassName }}
      priorityClassName: {{ $.Values.namespace }}-{{ $deploymentConfig.priorityClassName }}
      {{ end }}
      initContainers:
        - name: prepare-configuration
          image: {{ $.Values.swh_utils_image }}:{{ $.Values.swh_utils_image_version }}
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          args:
          - -c
          - eval echo "\"$(</etc/swh/configuration-template/config.yml.template)\"" > /etc/swh/config.yml
          env: {{ include "swh.secrets.envFromDeploymentConfig" (dict "deploymentConfig" $deploymentConfig
                                                                      "Values" $.Values) | nindent 10 }}
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
          - name: configuration-template
            mountPath: /etc/swh/configuration-template
          {{ include "swh.storage.cassandra.keyspaceManagementContainers"
            (dict "Values" $.Values
                  "configurationRef" $deploymentConfig.storageConfigurationRef
                  "imagePrefixName" "swh_storage_replayer_image") | nindent 8 }}

          {{- if $deploymentConfig.checkDbVersion }}
          {{ include "swh.checkDatabaseVersionContainer" (dict "Values" $.Values
                                                               "imagePrefixName" "swh_storage_replayer_image"
                                                               "module" "storage") | nindent 8 }}
          {{- end }}
      containers:
        - name: storage-replayer
          resources:
            requests:
              memory: {{ get $deploymentConfig "requestedMemory" | default "512Mi" }}
              cpu: {{ get $deploymentConfig "requestedCpu" | default "500m" }}
          {{- if or ( get $deploymentConfig "limitedCpu" ) ( get $deploymentConfig "limitedMemory" ) }}
            limits:
            {{- if ( get $deploymentConfig "limitedMemory" ) }}
              memory: {{ get $deploymentConfig "limitedMemory" }}
            {{- end }}
            {{- if ( get $deploymentConfig "limitedCpu" ) }}
              cpu: {{ get $deploymentConfig "limitedCpu" }}
            {{- end }}
          {{ end }}
          image: {{ $.Values.swh_storage_replayer_image }}:{{ $.Values.swh_storage_replayer_image_version }}
          command:
          - /bin/bash
          args:
          - -c
          - /opt/swh/entrypoint.sh
          env:
            - name: STATSD_HOST
              value: {{ $.Values.statsdExternalHost | default "prometheus-statsd-exporter" }}
            - name: STATSD_PORT
              value: {{ $.Values.statsdPort | default "9125" | quote }}
            - name: STATSD_TAGS
              value: deployment:storage-replayer-{{ $deployment }}
          {{- if $deploymentConfig.sentry.enabled }}
            - name: SWH_SENTRY_ENVIRONMENT
              value: {{ $.Values.sentry.environment }}
            - name: SWH_MAIN_PACKAGE
              value: swh.storage
            - name: SWH_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $deploymentConfig.sentry.secretKeyRef }}
                  key: {{ $deploymentConfig.sentry.secretKeyName }}
                  # 'name' secret must exist & include key "host"
                  optional: true
            - name: SWH_SENTRY_DISABLE_LOGGING_EVENTS
              value: "true"
          {{- end }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: configuration
            mountPath: /etc/swh
          - name: backend-utils
            mountPath: /entrypoints
      volumes:
      - name: configuration
        emptyDir: {}
      - name: configuration-template
        configMap:
          name: storage-replayer-configuration-{{ $deployment }}-template
          items:
          - key: "config.yml.template"
            path: "config.yml.template"
      - name: backend-utils
        configMap:
          name: backend-utils
          defaultMode: 0555
{{ end }}
{{ end }}
{{- end -}}
