{{- $namespace := .Values.namespace -}}
{{- $clusterName := .Values.clusterName -}}
{{- $vaultAuthRef := .Values.vaultAuthRef -}}
{{- $topLevelConfig := .Values.storageReplayer -}}
{{- with $topLevelConfig -}}
  {{- if and .enabled (ne $clusterName "local-cluster") -}}
    {{- $secrets := list -}}

    {{/* Extract secrets from the top level deployment config. */}}
    {{- $secretsDict := include "swh.secrets.dictFromDeploymentTopLevelConfig"
          (dict "deploymentConfig" $topLevelConfig
                "Values" $.Values) | fromYaml | default dict -}}

    {{- range $name, $secretConfig := $secretsDict -}}
      {{- $secretName := dig "secretKeyRef" "" $secretConfig -}}
      {{- if $secretName }}
        {{- $secrets = append $secrets (list $secretName $namespace) -}}
      {{- end }}
    {{- end }}

    {{/* Extract secrets from per deployment instance config, when enabled. */}}
    {{- range $deploymentName, $deploymentConfig := .deployments }}
      {{- if (ne false $deploymentConfig.enabled) -}}
        {{- $sentry := $deploymentConfig.sentry | default $topLevelConfig.sentry  -}}
        {{- $secretsDict = include "swh.secrets.dictFromDeploymentConfig"
               (dict "deploymentConfig" $deploymentConfig
                     "Values" $.Values) | fromYaml | default dict -}}

        {{- range $name, $secretConfig := $secretsDict -}}
          {{- $secretName := dig "secretKeyRef" "" $secretConfig -}}
          {{- if $secretName }}
            {{- $secrets = append $secrets (list $secretName $namespace) -}}
          {{- end }}
        {{- end }}

        {{- if and $sentry $sentry.enabled -}}
          {{- $secretName := dig "secretKeyRef" "" $sentry -}}
          {{- if $secretName }}
            {{- $secrets = append $secrets (list $secretName $namespace) -}}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- range $secret := uniq $secrets }}
      {{ $secretName := first $secret }}
      {{ $namespace := last $secret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}-vss
  namespace: {{ $namespace }}
spec:
  destination:
    create: true
    name: {{ $secretName }}
    overwrite: true
  mount: secrets-{{ $clusterName }}
  path: {{ $secretName }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: {{ $vaultAuthRef }}

    {{- end }}
  {{- end }}
{{- end }}
